always_for_in=true
always_use_return=false
format_docstrings=true
indent = 4
margin = 92
normalize_line_endings = "unix"
remove_extra_newlines=true
whitespace_in_kwargs=false
whitespace_ops_in_indices=true
whitespace_typedefs=true
