# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Arc

    Arc(;
        id=nothing,
        from=nothing,
        to=nothing,
    )

    - id::Int64
    - from::Float64
    - to::Float64
"""
Base.@kwdef mutable struct Arc <: OpenAPI.APIModel
    id::Union{Nothing,Int64} = nothing
    from::Union{Nothing,Float64} = nothing
    to::Union{Nothing,Float64} = nothing

    function Arc(id, from, to)
        OpenAPI.validate_property(Arc, Symbol("id"), id)
        OpenAPI.validate_property(Arc, Symbol("from"), from)
        OpenAPI.validate_property(Arc, Symbol("to"), to)
        return new(id, from, to)
    end
end # type Arc

const _property_types_Arc = Dict{Symbol,String}(
    Symbol("id") => "Int64",
    Symbol("from") => "Float64",
    Symbol("to") => "Float64",
)
OpenAPI.property_type(::Type{Arc}, name::Symbol) =
    Union{Nothing,eval(Base.Meta.parse(_property_types_Arc[name]))}

function check_required(o::Arc)
    o.id === nothing && (return false)
    o.from === nothing && (return false)
    o.to === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{Arc}, name::Symbol, val)



end
