# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""MarketBidCost_start_up
Start-up cost can take linear or multi-stage cost

    MarketBidCostStartUp(; value=nothing)
"""
mutable struct MarketBidCostStartUp <: OpenAPI.OneOfAPIModel
    value::Any # Union{ StartUpStages, TimeSeriesKey }
    MarketBidCostStartUp() = new()
    MarketBidCostStartUp(value) = new(value)
end # type MarketBidCostStartUp

function OpenAPI.property_type(
    ::Type{MarketBidCostStartUp},
    name::Symbol,
    json::Dict{String, Any},
)

    # no discriminator specified, can't determine the exact type
    return fieldtype(MarketBidCostStartUp, name)
end
