# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TurbinePump_1

    TurbinePump1(;
        turbine=nothing,
        pump=nothing,
    )

    - turbine::Float64
    - pump::Float64
"""
Base.@kwdef mutable struct TurbinePump1 <: OpenAPI.APIModel
    turbine::Union{Nothing, Float64} = nothing
    pump::Union{Nothing, Float64} = nothing

    function TurbinePump1(turbine, pump, )
        OpenAPI.validate_property(TurbinePump1, Symbol("turbine"), turbine)
        OpenAPI.validate_property(TurbinePump1, Symbol("pump"), pump)
        return new(turbine, pump, )
    end
end # type TurbinePump1

const _property_types_TurbinePump1 = Dict{Symbol,String}(Symbol("turbine")=>"Float64", Symbol("pump")=>"Float64", )
OpenAPI.property_type(::Type{ TurbinePump1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TurbinePump1[name]))}

function check_required(o::TurbinePump1)
    o.turbine === nothing && (return false)
    o.pump === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ TurbinePump1 }, name::Symbol, val)


end
