# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""PowerLoad

    PowerLoad(;
        id=nothing,
        name=nothing,
        available=nothing,
        bus=nothing,
        active_power=nothing,
        reactive_power=nothing,
        base_power=nothing,
        max_active_power=nothing,
        max_reactive_power=nothing,
        conformity="UNDEFINED",
        dynamic_injector=nothing,
    )

    - id::Int64
    - name::String
    - available::Bool
    - bus::Int64
    - active_power::Float64
    - reactive_power::Float64
    - base_power::Float64
    - max_active_power::Float64
    - max_reactive_power::Float64
    - conformity::String
    - dynamic_injector::Any
"""
Base.@kwdef mutable struct PowerLoad <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    bus::Union{Nothing, Int64} = nothing
    active_power::Union{Nothing, Float64} = nothing
    reactive_power::Union{Nothing, Float64} = nothing
    base_power::Union{Nothing, Float64} = nothing
    max_active_power::Union{Nothing, Float64} = nothing
    max_reactive_power::Union{Nothing, Float64} = nothing
    conformity::Union{Nothing, String} = "UNDEFINED"
    dynamic_injector::Union{Nothing, Any} = nothing

    function PowerLoad(
        id,
        name,
        available,
        bus,
        active_power,
        reactive_power,
        base_power,
        max_active_power,
        max_reactive_power,
        conformity,
        dynamic_injector,
    )
        o = new(
            id,
            name,
            available,
            bus,
            active_power,
            reactive_power,
            base_power,
            max_active_power,
            max_reactive_power,
            conformity,
            dynamic_injector,
        )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PowerLoad

const _property_types_PowerLoad = Dict{Symbol, String}(
    Symbol("id")=>"Int64",
    Symbol("name")=>"String",
    Symbol("available")=>"Bool",
    Symbol("bus")=>"Int64",
    Symbol("active_power")=>"Float64",
    Symbol("reactive_power")=>"Float64",
    Symbol("base_power")=>"Float64",
    Symbol("max_active_power")=>"Float64",
    Symbol("max_reactive_power")=>"Float64",
    Symbol("conformity")=>"String",
    Symbol("dynamic_injector")=>"Any",
)
OpenAPI.property_type(::Type{PowerLoad}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_PowerLoad[name]))}

function OpenAPI.check_required(o::PowerLoad)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.bus === nothing && (return false)
    o.active_power === nothing && (return false)
    o.reactive_power === nothing && (return false)
    o.base_power === nothing && (return false)
    o.max_active_power === nothing && (return false)
    o.max_reactive_power === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PowerLoad)
    OpenAPI.validate_property(PowerLoad, Symbol("id"), o.id)
    OpenAPI.validate_property(PowerLoad, Symbol("name"), o.name)
    OpenAPI.validate_property(PowerLoad, Symbol("available"), o.available)
    OpenAPI.validate_property(PowerLoad, Symbol("bus"), o.bus)
    OpenAPI.validate_property(PowerLoad, Symbol("active_power"), o.active_power)
    OpenAPI.validate_property(PowerLoad, Symbol("reactive_power"), o.reactive_power)
    OpenAPI.validate_property(PowerLoad, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(PowerLoad, Symbol("max_active_power"), o.max_active_power)
    OpenAPI.validate_property(PowerLoad, Symbol("max_reactive_power"), o.max_reactive_power)
    OpenAPI.validate_property(PowerLoad, Symbol("conformity"), o.conformity)
    OpenAPI.validate_property(PowerLoad, Symbol("dynamic_injector"), o.dynamic_injector)
end

function OpenAPI.validate_property(::Type{PowerLoad}, name::Symbol, val)
    if name === Symbol("conformity")
        OpenAPI.validate_param(
            name,
            "PowerLoad",
            :enum,
            val,
            ["NON_CONFORMING", "CONFORMING", "UNDEFINED"],
        )
    end
end
