# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""MarketBidCost_decremental_offer_curves
Buy Offer Curves data

    MarketBidCostDecrementalOfferCurves(; value=nothing)
"""
mutable struct MarketBidCostDecrementalOfferCurves <: OpenAPI.OneOfAPIModel
    value::Any # Union{ PiecewiseStepData, TimeSeriesKey }
    MarketBidCostDecrementalOfferCurves() = new()
    MarketBidCostDecrementalOfferCurves(value) = new(value)
end # type MarketBidCostDecrementalOfferCurves

function OpenAPI.property_type(
    ::Type{MarketBidCostDecrementalOfferCurves},
    name::Symbol,
    json::Dict{String, Any},
)

    # no discriminator specified, can't determine the exact type
    return fieldtype(MarketBidCostDecrementalOfferCurves, name)
end
