# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Fdbd_pnts

    FdbdPnts(;
        fdbd1=nothing,
        fdbd2=nothing,
    )

    - fdbd1::Float64
    - fdbd2::Float64
"""
Base.@kwdef mutable struct FdbdPnts <: OpenAPI.APIModel
    fdbd1::Union{Nothing, Float64} = nothing
    fdbd2::Union{Nothing, Float64} = nothing

    function FdbdPnts(fdbd1, fdbd2, )
        o = new(fdbd1, fdbd2, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type FdbdPnts

const _property_types_FdbdPnts = Dict{Symbol,String}(Symbol("fdbd1")=>"Float64", Symbol("fdbd2")=>"Float64", )
OpenAPI.property_type(::Type{ FdbdPnts }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FdbdPnts[name]))}

function OpenAPI.check_required(o::FdbdPnts)
    true
end

function OpenAPI.validate_properties(o::FdbdPnts)
    OpenAPI.validate_property(FdbdPnts, Symbol("fdbd1"), o.fdbd1)
    OpenAPI.validate_property(FdbdPnts, Symbol("fdbd2"), o.fdbd2)
end

function OpenAPI.validate_property(::Type{ FdbdPnts }, name::Symbol, val)


end
