# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""operation_cost

    OperationCost(; value=nothing)
"""
mutable struct OperationCost <: OpenAPI.OneOfAPIModel
    value::Any # Union{ HydroGenerationCost, StorageCost }
    OperationCost() = new()
    OperationCost(value) = new(value)
end # type OperationCost

function OpenAPI.property_type(::Type{ OperationCost }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(OperationCost, name)
end
