# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Line_arc

    LineArc(;
        from=nothing,
        to=nothing,
    )

    - from::Float64
    - to::Float64
"""
Base.@kwdef mutable struct LineArc <: OpenAPI.APIModel
    from::Union{Nothing,Float64} = nothing
    to::Union{Nothing,Float64} = nothing

    function LineArc(from, to)
        OpenAPI.validate_property(LineArc, Symbol("from"), from)
        OpenAPI.validate_property(LineArc, Symbol("to"), to)
        return new(from, to)
    end
end # type LineArc

const _property_types_LineArc =
    Dict{Symbol,String}(Symbol("from") => "Float64", Symbol("to") => "Float64")
OpenAPI.property_type(::Type{LineArc}, name::Symbol) =
    Union{Nothing,eval(Base.Meta.parse(_property_types_LineArc[name]))}

function check_required(o::LineArc)
    true
end

function OpenAPI.validate_property(::Type{LineArc}, name::Symbol, val)


end
