# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""TapTransformer

    TapTransformer(;
        id=nothing,
        name=nothing,
        available=nothing,
        active_power_flow=nothing,
        reactive_power_flow=nothing,
        arc=nothing,
        r=nothing,
        x=nothing,
        primary_shunt=nothing,
        tap=nothing,
        rating=nothing,
        rating_b=nothing,
        rating_c=nothing,
    )

    - id::Int64
    - name::String
    - available::Bool
    - active_power_flow::Float64
    - reactive_power_flow::Float64
    - arc::Int64
    - r::Float64
    - x::Float64
    - primary_shunt::Float64
    - tap::Float64
    - rating::Float64
    - rating_b::Float64
    - rating_c::Float64
"""
Base.@kwdef mutable struct TapTransformer <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    reactive_power_flow::Union{Nothing, Float64} = nothing
    arc::Union{Nothing, Int64} = nothing
    r::Union{Nothing, Float64} = nothing
    x::Union{Nothing, Float64} = nothing
    primary_shunt::Union{Nothing, Float64} = nothing
    tap::Union{Nothing, Float64} = nothing
    rating::Union{Nothing, Float64} = nothing
    rating_b::Union{Nothing, Float64} = nothing
    rating_c::Union{Nothing, Float64} = nothing

    function TapTransformer(
        id,
        name,
        available,
        active_power_flow,
        reactive_power_flow,
        arc,
        r,
        x,
        primary_shunt,
        tap,
        rating,
        rating_b,
        rating_c,
    )
        o = new(
            id,
            name,
            available,
            active_power_flow,
            reactive_power_flow,
            arc,
            r,
            x,
            primary_shunt,
            tap,
            rating,
            rating_b,
            rating_c,
        )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TapTransformer

const _property_types_TapTransformer = Dict{Symbol, String}(
    Symbol("id") => "Int64",
    Symbol("name") => "String",
    Symbol("available") => "Bool",
    Symbol("active_power_flow") => "Float64",
    Symbol("reactive_power_flow") => "Float64",
    Symbol("arc") => "Int64",
    Symbol("r") => "Float64",
    Symbol("x") => "Float64",
    Symbol("primary_shunt") => "Float64",
    Symbol("tap") => "Float64",
    Symbol("rating") => "Float64",
    Symbol("rating_b") => "Float64",
    Symbol("rating_c") => "Float64",
)
OpenAPI.property_type(::Type{TapTransformer}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_TapTransformer[name]))}

function OpenAPI.check_required(o::TapTransformer)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.reactive_power_flow === nothing && (return false)
    o.arc === nothing && (return false)
    o.r === nothing && (return false)
    o.x === nothing && (return false)
    o.primary_shunt === nothing && (return false)
    o.tap === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TapTransformer)
    OpenAPI.validate_property(TapTransformer, Symbol("id"), o.id)
    OpenAPI.validate_property(TapTransformer, Symbol("name"), o.name)
    OpenAPI.validate_property(TapTransformer, Symbol("available"), o.available)
    OpenAPI.validate_property(
        TapTransformer,
        Symbol("active_power_flow"),
        o.active_power_flow,
    )
    OpenAPI.validate_property(
        TapTransformer,
        Symbol("reactive_power_flow"),
        o.reactive_power_flow,
    )
    OpenAPI.validate_property(TapTransformer, Symbol("arc"), o.arc)
    OpenAPI.validate_property(TapTransformer, Symbol("r"), o.r)
    OpenAPI.validate_property(TapTransformer, Symbol("x"), o.x)
    OpenAPI.validate_property(TapTransformer, Symbol("primary_shunt"), o.primary_shunt)
    OpenAPI.validate_property(TapTransformer, Symbol("tap"), o.tap)
    OpenAPI.validate_property(TapTransformer, Symbol("rating"), o.rating)
    OpenAPI.validate_property(TapTransformer, Symbol("rating_b"), o.rating_b)
    OpenAPI.validate_property(TapTransformer, Symbol("rating_c"), o.rating_c)
end

function OpenAPI.validate_property(::Type{TapTransformer}, name::Symbol, val) end
