# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""FromTo

    FromTo(;
        from=nothing,
        to=nothing,
    )

    - from::Float64
    - to::Float64
"""
Base.@kwdef mutable struct FromTo <: OpenAPI.APIModel
    from::Union{Nothing, Float64} = nothing
    to::Union{Nothing, Float64} = nothing

    function FromTo(from, to)
        o = new(from, to)
        OpenAPI.validate_properties(o)
        return o
    end
end # type FromTo

const _property_types_FromTo =
    Dict{Symbol, String}(Symbol("from")=>"Float64", Symbol("to")=>"Float64")
OpenAPI.property_type(::Type{FromTo}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_FromTo[name]))}

function OpenAPI.check_required(o::FromTo)
    true
end

function OpenAPI.validate_properties(o::FromTo)
    OpenAPI.validate_property(FromTo, Symbol("from"), o.from)
    OpenAPI.validate_property(FromTo, Symbol("to"), o.to)
end

function OpenAPI.validate_property(::Type{FromTo}, name::Symbol, val) end
