# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""TwoTerminalLoss

    TwoTerminalLoss(; value=nothing)
"""
mutable struct TwoTerminalLoss <: OpenAPI.OneOfAPIModel
    value::Any # Union{ IncrementalCurve, InputOutputCurve }
    TwoTerminalLoss() = new()
    TwoTerminalLoss(value) = new(value)
end # type TwoTerminalLoss

function OpenAPI.property_type(::Type{ TwoTerminalLoss }, name::Symbol, json::Dict{String,Any})
    discriminator = json["curve_type"]
    if discriminator == "INCREMENTAL"
        return eval(Base.Meta.parse("IncrementalCurve"))
    elseif discriminator == "INPUT_OUTPUT"
        return eval(Base.Meta.parse("InputOutputCurve"))
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for TwoTerminalLoss"))
end
