# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ThermalStandard

    ThermalStandard(;
        id=nothing,
        name=nothing,
        available=nothing,
        status=nothing,
        bus=nothing,
        active_power=nothing,
        reactive_power=nothing,
        rating=nothing,
        active_power_limits=nothing,
        reactive_power_limits=nothing,
        ramp_limits=nothing,
        operation_cost=nothing,
        base_power=0.0,
        time_limits=nothing,
        must_run=false,
        prime_mover_type="OT",
        fuel_type="OTHER",
        time_at_status=10000.0,
        dynamic_injector=nothing,
    )

    - id::Int64
    - name::String
    - available::Bool
    - status::Bool
    - bus::Int64
    - active_power::Float64
    - reactive_power::Float64
    - rating::Float64
    - active_power_limits::MinMax
    - reactive_power_limits::MinMax
    - ramp_limits::UpDown
    - operation_cost::ThermalGenerationCost
    - base_power::Float64
    - time_limits::UpDown
    - must_run::Bool
    - prime_mover_type::String
    - fuel_type::String : Thermal fuels that reflect options in the EIA annual energy review.
    - time_at_status::Float64
    - dynamic_injector::Any
"""
Base.@kwdef mutable struct ThermalStandard <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    status::Union{Nothing, Bool} = nothing
    bus::Union{Nothing, Int64} = nothing
    active_power::Union{Nothing, Float64} = nothing
    reactive_power::Union{Nothing, Float64} = nothing
    rating::Union{Nothing, Float64} = nothing
    active_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    reactive_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    ramp_limits = nothing # spec type: Union{ Nothing, UpDown }
    operation_cost = nothing # spec type: Union{ Nothing, ThermalGenerationCost }
    base_power::Union{Nothing, Float64} = 0.0
    time_limits = nothing # spec type: Union{ Nothing, UpDown }
    must_run::Union{Nothing, Bool} = false
    prime_mover_type::Union{Nothing, String} = "OT"
    fuel_type::Union{Nothing, String} = "OTHER"
    time_at_status::Union{Nothing, Float64} = 10000.0
    dynamic_injector::Union{Nothing, Any} = nothing

    function ThermalStandard(id, name, available, status, bus, active_power, reactive_power, rating, active_power_limits, reactive_power_limits, ramp_limits, operation_cost, base_power, time_limits, must_run, prime_mover_type, fuel_type, time_at_status, dynamic_injector, )
        OpenAPI.validate_property(ThermalStandard, Symbol("id"), id)
        OpenAPI.validate_property(ThermalStandard, Symbol("name"), name)
        OpenAPI.validate_property(ThermalStandard, Symbol("available"), available)
        OpenAPI.validate_property(ThermalStandard, Symbol("status"), status)
        OpenAPI.validate_property(ThermalStandard, Symbol("bus"), bus)
        OpenAPI.validate_property(ThermalStandard, Symbol("active_power"), active_power)
        OpenAPI.validate_property(ThermalStandard, Symbol("reactive_power"), reactive_power)
        OpenAPI.validate_property(ThermalStandard, Symbol("rating"), rating)
        OpenAPI.validate_property(ThermalStandard, Symbol("active_power_limits"), active_power_limits)
        OpenAPI.validate_property(ThermalStandard, Symbol("reactive_power_limits"), reactive_power_limits)
        OpenAPI.validate_property(ThermalStandard, Symbol("ramp_limits"), ramp_limits)
        OpenAPI.validate_property(ThermalStandard, Symbol("operation_cost"), operation_cost)
        OpenAPI.validate_property(ThermalStandard, Symbol("base_power"), base_power)
        OpenAPI.validate_property(ThermalStandard, Symbol("time_limits"), time_limits)
        OpenAPI.validate_property(ThermalStandard, Symbol("must_run"), must_run)
        OpenAPI.validate_property(ThermalStandard, Symbol("prime_mover_type"), prime_mover_type)
        OpenAPI.validate_property(ThermalStandard, Symbol("fuel_type"), fuel_type)
        OpenAPI.validate_property(ThermalStandard, Symbol("time_at_status"), time_at_status)
        OpenAPI.validate_property(ThermalStandard, Symbol("dynamic_injector"), dynamic_injector)
        return new(id, name, available, status, bus, active_power, reactive_power, rating, active_power_limits, reactive_power_limits, ramp_limits, operation_cost, base_power, time_limits, must_run, prime_mover_type, fuel_type, time_at_status, dynamic_injector, )
    end
end # type ThermalStandard

const _property_types_ThermalStandard = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("status")=>"Bool", Symbol("bus")=>"Int64", Symbol("active_power")=>"Float64", Symbol("reactive_power")=>"Float64", Symbol("rating")=>"Float64", Symbol("active_power_limits")=>"MinMax", Symbol("reactive_power_limits")=>"MinMax", Symbol("ramp_limits")=>"UpDown", Symbol("operation_cost")=>"ThermalGenerationCost", Symbol("base_power")=>"Float64", Symbol("time_limits")=>"UpDown", Symbol("must_run")=>"Bool", Symbol("prime_mover_type")=>"String", Symbol("fuel_type")=>"String", Symbol("time_at_status")=>"Float64", Symbol("dynamic_injector")=>"Any", )
OpenAPI.property_type(::Type{ ThermalStandard }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ThermalStandard[name]))}

function check_required(o::ThermalStandard)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.status === nothing && (return false)
    o.bus === nothing && (return false)
    o.active_power === nothing && (return false)
    o.reactive_power === nothing && (return false)
    o.rating === nothing && (return false)
    o.active_power_limits === nothing && (return false)
    o.operation_cost === nothing && (return false)
    o.base_power === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ThermalStandard }, name::Symbol, val)
















    if name === Symbol("prime_mover_type")
        OpenAPI.validate_param(name, "ThermalStandard", :enum, val, ["BA", "BT", "CA", "CC", "CE", "CP", "CS", "CT", "ES", "FC", "FW", "GT", "HA", "HB", "HK", "HY", "IC", "PS", "OT", "ST", "PVe", "WT", "WS"])
    end


    if name === Symbol("fuel_type")
        OpenAPI.validate_param(name, "ThermalStandard", :enum, val, ["COAL", "ANTHRACITE_COAL", "BITUMINOUS_COAL", "LIGNITE_COAL", "SUBBITUMINOUS_COAL", "WASTE_COAL", "REFINED_COAL", "SYNTHESIS_GAS_COAL", "DISTILLATE_FUEL_OIL", "JET_FUEL", "KEROSENE", "PETROLEUM_COKE", "RESIDUAL_FUEL_OIL", "PROPANE", "SYNTHESIS_GAS_PETROLEUM_COKE", "WASTE_OIL", "BLASTE_FURNACE_GAS", "NATURAL_GAS", "OTHER_GAS", "AG_BYPRODUCT", "MUNICIPAL_WASTE", "OTHER_BIOMASS_SOLIDS", "WOOD_WASTE_SOLIDS", "OTHER_BIOMASS_LIQUIDS", "SLUDGE_WASTE", "BLACK_LIQUOR", "WOOD_WASTE_LIQUIDS", "LANDFILL_GAS", "OTHEHR_BIOMASS_GAS", "NUCLEAR", "WASTE_HEAT", "TIREDERIVED_FUEL", "OTHER"])
    end



end
