# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ActiveRenewableControllerAB

    ActiveRenewableControllerAB(;
        id=nothing,
        bus_control=nothing,
        from_branch_control=nothing,
        to_branch_control=nothing,
        branch_id_control=nothing,
        Freq_Flag=nothing,
        K_pg=nothing,
        K_ig=nothing,
        T_p=nothing,
        fdbd_pnts=nothing,
        fe_lim=nothing,
        P_lim=nothing,
        T_g=nothing,
        D_dn=nothing,
        D_up=nothing,
        dP_lim=nothing,
        P_lim_inner=nothing,
        T_pord=nothing,
        P_ref=1.0,
        states=nothing,
        n_states=nothing,
    )

    - id::Int64
    - bus_control::Int64
    - from_branch_control::Int64
    - to_branch_control::Int64
    - branch_id_control::String
    - Freq_Flag::Bool
    - K_pg::Float64
    - K_ig::Float64
    - T_p::Float64
    - fdbd_pnts::FdbdPnts
    - fe_lim::MinMax
    - P_lim::MinMax
    - T_g::Float64
    - D_dn::Float64
    - D_up::Float64
    - dP_lim::MinMax
    - P_lim_inner::MinMax
    - T_pord::Float64
    - P_ref::Float64
    - states::Vector{String} : States of the ActiveRenewableControllerAB model (dependent on the Flag)
    - n_states::Int64 : Number of states (dependent on the Flag)
"""
Base.@kwdef mutable struct ActiveRenewableControllerAB <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    bus_control::Union{Nothing, Int64} = nothing
    from_branch_control::Union{Nothing, Int64} = nothing
    to_branch_control::Union{Nothing, Int64} = nothing
    branch_id_control::Union{Nothing, String} = nothing
    Freq_Flag::Union{Nothing, Bool} = nothing
    K_pg::Union{Nothing, Float64} = nothing
    K_ig::Union{Nothing, Float64} = nothing
    T_p::Union{Nothing, Float64} = nothing
    fdbd_pnts = nothing # spec type: Union{ Nothing, FdbdPnts }
    fe_lim = nothing # spec type: Union{ Nothing, MinMax }
    P_lim = nothing # spec type: Union{ Nothing, MinMax }
    T_g::Union{Nothing, Float64} = nothing
    D_dn::Union{Nothing, Float64} = nothing
    D_up::Union{Nothing, Float64} = nothing
    dP_lim = nothing # spec type: Union{ Nothing, MinMax }
    P_lim_inner = nothing # spec type: Union{ Nothing, MinMax }
    T_pord::Union{Nothing, Float64} = nothing
    P_ref::Union{Nothing, Float64} = 1.0
    states::Union{Nothing, Vector{String}} = nothing
    n_states::Union{Nothing, Int64} = nothing

    function ActiveRenewableControllerAB(id, bus_control, from_branch_control, to_branch_control, branch_id_control, Freq_Flag, K_pg, K_ig, T_p, fdbd_pnts, fe_lim, P_lim, T_g, D_dn, D_up, dP_lim, P_lim_inner, T_pord, P_ref, states, n_states, )
        o = new(id, bus_control, from_branch_control, to_branch_control, branch_id_control, Freq_Flag, K_pg, K_ig, T_p, fdbd_pnts, fe_lim, P_lim, T_g, D_dn, D_up, dP_lim, P_lim_inner, T_pord, P_ref, states, n_states, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ActiveRenewableControllerAB

const _property_types_ActiveRenewableControllerAB = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("bus_control")=>"Int64", Symbol("from_branch_control")=>"Int64", Symbol("to_branch_control")=>"Int64", Symbol("branch_id_control")=>"String", Symbol("Freq_Flag")=>"Bool", Symbol("K_pg")=>"Float64", Symbol("K_ig")=>"Float64", Symbol("T_p")=>"Float64", Symbol("fdbd_pnts")=>"FdbdPnts", Symbol("fe_lim")=>"MinMax", Symbol("P_lim")=>"MinMax", Symbol("T_g")=>"Float64", Symbol("D_dn")=>"Float64", Symbol("D_up")=>"Float64", Symbol("dP_lim")=>"MinMax", Symbol("P_lim_inner")=>"MinMax", Symbol("T_pord")=>"Float64", Symbol("P_ref")=>"Float64", Symbol("states")=>"Vector{String}", Symbol("n_states")=>"Int64", )
OpenAPI.property_type(::Type{ ActiveRenewableControllerAB }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ActiveRenewableControllerAB[name]))}

function OpenAPI.check_required(o::ActiveRenewableControllerAB)
    o.id === nothing && (return false)
    o.bus_control === nothing && (return false)
    o.from_branch_control === nothing && (return false)
    o.to_branch_control === nothing && (return false)
    o.branch_id_control === nothing && (return false)
    o.Freq_Flag === nothing && (return false)
    o.K_pg === nothing && (return false)
    o.K_ig === nothing && (return false)
    o.T_p === nothing && (return false)
    o.fdbd_pnts === nothing && (return false)
    o.fe_lim === nothing && (return false)
    o.P_lim === nothing && (return false)
    o.T_g === nothing && (return false)
    o.D_dn === nothing && (return false)
    o.D_up === nothing && (return false)
    o.dP_lim === nothing && (return false)
    o.P_lim_inner === nothing && (return false)
    o.states === nothing && (return false)
    o.n_states === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ActiveRenewableControllerAB)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("id"), o.id)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("bus_control"), o.bus_control)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("from_branch_control"), o.from_branch_control)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("to_branch_control"), o.to_branch_control)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("branch_id_control"), o.branch_id_control)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("Freq_Flag"), o.Freq_Flag)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("K_pg"), o.K_pg)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("K_ig"), o.K_ig)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("T_p"), o.T_p)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("fdbd_pnts"), o.fdbd_pnts)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("fe_lim"), o.fe_lim)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("P_lim"), o.P_lim)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("T_g"), o.T_g)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("D_dn"), o.D_dn)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("D_up"), o.D_up)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("dP_lim"), o.dP_lim)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("P_lim_inner"), o.P_lim_inner)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("T_pord"), o.T_pord)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("P_ref"), o.P_ref)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("states"), o.states)
    OpenAPI.validate_property(ActiveRenewableControllerAB, Symbol("n_states"), o.n_states)
end

function OpenAPI.validate_property(::Type{ ActiveRenewableControllerAB }, name::Symbol, val)





















end
