# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ConstantReserve

    ConstantReserve(;
        id=nothing,
        name=nothing,
        available=nothing,
        time_frame=nothing,
        requirement=nothing,
        sustained_time=3600.0,
        max_output_fraction=1.0,
        max_participation_factor=1.0,
        deployed_fraction=0.0,
        reserve_direction=nothing,
    )

    - id::Int64
    - name::String
    - available::Bool
    - time_frame::Float64
    - requirement::Float64
    - sustained_time::Float64
    - max_output_fraction::Float64
    - max_participation_factor::Float64
    - deployed_fraction::Float64
    - reserve_direction::String
"""
Base.@kwdef mutable struct ConstantReserve <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    time_frame::Union{Nothing, Float64} = nothing
    requirement::Union{Nothing, Float64} = nothing
    sustained_time::Union{Nothing, Float64} = 3600.0
    max_output_fraction::Union{Nothing, Float64} = 1.0
    max_participation_factor::Union{Nothing, Float64} = 1.0
    deployed_fraction::Union{Nothing, Float64} = 0.0
    reserve_direction::Union{Nothing, String} = nothing

    function ConstantReserve(id, name, available, time_frame, requirement, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, reserve_direction, )
        OpenAPI.validate_property(ConstantReserve, Symbol("id"), id)
        OpenAPI.validate_property(ConstantReserve, Symbol("name"), name)
        OpenAPI.validate_property(ConstantReserve, Symbol("available"), available)
        OpenAPI.validate_property(ConstantReserve, Symbol("time_frame"), time_frame)
        OpenAPI.validate_property(ConstantReserve, Symbol("requirement"), requirement)
        OpenAPI.validate_property(ConstantReserve, Symbol("sustained_time"), sustained_time)
        OpenAPI.validate_property(ConstantReserve, Symbol("max_output_fraction"), max_output_fraction)
        OpenAPI.validate_property(ConstantReserve, Symbol("max_participation_factor"), max_participation_factor)
        OpenAPI.validate_property(ConstantReserve, Symbol("deployed_fraction"), deployed_fraction)
        OpenAPI.validate_property(ConstantReserve, Symbol("reserve_direction"), reserve_direction)
        return new(id, name, available, time_frame, requirement, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, reserve_direction, )
    end
end # type ConstantReserve

const _property_types_ConstantReserve = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("time_frame")=>"Float64", Symbol("requirement")=>"Float64", Symbol("sustained_time")=>"Float64", Symbol("max_output_fraction")=>"Float64", Symbol("max_participation_factor")=>"Float64", Symbol("deployed_fraction")=>"Float64", Symbol("reserve_direction")=>"String", )
OpenAPI.property_type(::Type{ ConstantReserve }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConstantReserve[name]))}

function check_required(o::ConstantReserve)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.time_frame === nothing && (return false)
    o.requirement === nothing && (return false)
    o.reserve_direction === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ConstantReserve }, name::Symbol, val)










    if name === Symbol("reserve_direction")
        OpenAPI.validate_param(name, "ConstantReserve", :enum, val, ["UP", "DOWN", "SYMMETRIC"])
    end

end
