# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RECurrentControlB

    RECurrentControlB(;
        id=nothing,
        Q_Flag=nothing,
        PQ_Flag=nothing,
        Vdip_lim=nothing,
        T_rv=nothing,
        dbd_pnts=nothing,
        K_qv=nothing,
        Iqinj_lim=nothing,
        V_ref0=nothing,
        K_vp=nothing,
        K_vi=nothing,
        T_iq=nothing,
        I_max=nothing,
    )

    - id::Int64
    - Q_Flag::Bool
    - PQ_Flag::Bool
    - Vdip_lim::MinMax
    - T_rv::Float64
    - dbd_pnts::DbdPnts
    - K_qv::Float64
    - Iqinj_lim::MinMax
    - V_ref0::Float64
    - K_vp::Float64
    - K_vi::Float64
    - T_iq::Float64
    - I_max::Float64
"""
Base.@kwdef mutable struct RECurrentControlB <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    Q_Flag::Union{Nothing, Bool} = nothing
    PQ_Flag::Union{Nothing, Bool} = nothing
    Vdip_lim = nothing # spec type: Union{ Nothing, MinMax }
    T_rv::Union{Nothing, Float64} = nothing
    dbd_pnts = nothing # spec type: Union{ Nothing, DbdPnts }
    K_qv::Union{Nothing, Float64} = nothing
    Iqinj_lim = nothing # spec type: Union{ Nothing, MinMax }
    V_ref0::Union{Nothing, Float64} = nothing
    K_vp::Union{Nothing, Float64} = nothing
    K_vi::Union{Nothing, Float64} = nothing
    T_iq::Union{Nothing, Float64} = nothing
    I_max::Union{Nothing, Float64} = nothing

    function RECurrentControlB(id, Q_Flag, PQ_Flag, Vdip_lim, T_rv, dbd_pnts, K_qv, Iqinj_lim, V_ref0, K_vp, K_vi, T_iq, I_max, )
        o = new(id, Q_Flag, PQ_Flag, Vdip_lim, T_rv, dbd_pnts, K_qv, Iqinj_lim, V_ref0, K_vp, K_vi, T_iq, I_max, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RECurrentControlB

const _property_types_RECurrentControlB = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("Q_Flag")=>"Bool", Symbol("PQ_Flag")=>"Bool", Symbol("Vdip_lim")=>"MinMax", Symbol("T_rv")=>"Float64", Symbol("dbd_pnts")=>"DbdPnts", Symbol("K_qv")=>"Float64", Symbol("Iqinj_lim")=>"MinMax", Symbol("V_ref0")=>"Float64", Symbol("K_vp")=>"Float64", Symbol("K_vi")=>"Float64", Symbol("T_iq")=>"Float64", Symbol("I_max")=>"Float64", )
OpenAPI.property_type(::Type{ RECurrentControlB }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RECurrentControlB[name]))}

function OpenAPI.check_required(o::RECurrentControlB)
    o.id === nothing && (return false)
    o.Q_Flag === nothing && (return false)
    o.PQ_Flag === nothing && (return false)
    o.Vdip_lim === nothing && (return false)
    o.T_rv === nothing && (return false)
    o.dbd_pnts === nothing && (return false)
    o.K_qv === nothing && (return false)
    o.Iqinj_lim === nothing && (return false)
    o.V_ref0 === nothing && (return false)
    o.K_vp === nothing && (return false)
    o.K_vi === nothing && (return false)
    o.T_iq === nothing && (return false)
    o.I_max === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::RECurrentControlB)
    OpenAPI.validate_property(RECurrentControlB, Symbol("id"), o.id)
    OpenAPI.validate_property(RECurrentControlB, Symbol("Q_Flag"), o.Q_Flag)
    OpenAPI.validate_property(RECurrentControlB, Symbol("PQ_Flag"), o.PQ_Flag)
    OpenAPI.validate_property(RECurrentControlB, Symbol("Vdip_lim"), o.Vdip_lim)
    OpenAPI.validate_property(RECurrentControlB, Symbol("T_rv"), o.T_rv)
    OpenAPI.validate_property(RECurrentControlB, Symbol("dbd_pnts"), o.dbd_pnts)
    OpenAPI.validate_property(RECurrentControlB, Symbol("K_qv"), o.K_qv)
    OpenAPI.validate_property(RECurrentControlB, Symbol("Iqinj_lim"), o.Iqinj_lim)
    OpenAPI.validate_property(RECurrentControlB, Symbol("V_ref0"), o.V_ref0)
    OpenAPI.validate_property(RECurrentControlB, Symbol("K_vp"), o.K_vp)
    OpenAPI.validate_property(RECurrentControlB, Symbol("K_vi"), o.K_vi)
    OpenAPI.validate_property(RECurrentControlB, Symbol("T_iq"), o.T_iq)
    OpenAPI.validate_property(RECurrentControlB, Symbol("I_max"), o.I_max)
end

function OpenAPI.validate_property(::Type{ RECurrentControlB }, name::Symbol, val)













end
