# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RoundRotorMachine

    RoundRotorMachine(;
        id=nothing,
        R=nothing,
        Td0_p=nothing,
        Td0_pp=nothing,
        Tq0_p=nothing,
        Tq0_pp=nothing,
        Xd=nothing,
        Xq=nothing,
        Xd_p=nothing,
        Xq_p=nothing,
        Xd_pp=nothing,
        Xl=nothing,
        Se=nothing,
        gamma_d1=nothing,
        gamma_q1=nothing,
        gamma_d2=nothing,
        gamma_q2=nothing,
        gamma_qd=nothing,
    )

    - id::Int64
    - R::Float64
    - Td0_p::Float64
    - Td0_pp::Float64
    - Tq0_p::Float64
    - Tq0_pp::Float64
    - Xd::Float64
    - Xq::Float64
    - Xd_p::Float64
    - Xq_p::Float64
    - Xd_pp::Float64
    - Xl::Float64
    - Se::Vector{Float64} : this is meant to be a tuple, should we do this another way?
    - gamma_d1::Float64 : Do not modify
    - gamma_q1::Float64 : Do not modify
    - gamma_d2::Float64 : Do not modify
    - gamma_q2::Float64 : Do not modify
    - gamma_qd::Float64 : Do not modify
"""
Base.@kwdef mutable struct RoundRotorMachine <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    R::Union{Nothing, Float64} = nothing
    Td0_p::Union{Nothing, Float64} = nothing
    Td0_pp::Union{Nothing, Float64} = nothing
    Tq0_p::Union{Nothing, Float64} = nothing
    Tq0_pp::Union{Nothing, Float64} = nothing
    Xd::Union{Nothing, Float64} = nothing
    Xq::Union{Nothing, Float64} = nothing
    Xd_p::Union{Nothing, Float64} = nothing
    Xq_p::Union{Nothing, Float64} = nothing
    Xd_pp::Union{Nothing, Float64} = nothing
    Xl::Union{Nothing, Float64} = nothing
    Se::Union{Nothing, Vector{Float64}} = nothing
    gamma_d1::Union{Nothing, Float64} = nothing
    gamma_q1::Union{Nothing, Float64} = nothing
    gamma_d2::Union{Nothing, Float64} = nothing
    gamma_q2::Union{Nothing, Float64} = nothing
    gamma_qd::Union{Nothing, Float64} = nothing

    function RoundRotorMachine(id, R, Td0_p, Td0_pp, Tq0_p, Tq0_pp, Xd, Xq, Xd_p, Xq_p, Xd_pp, Xl, Se, gamma_d1, gamma_q1, gamma_d2, gamma_q2, gamma_qd, )
        o = new(id, R, Td0_p, Td0_pp, Tq0_p, Tq0_pp, Xd, Xq, Xd_p, Xq_p, Xd_pp, Xl, Se, gamma_d1, gamma_q1, gamma_d2, gamma_q2, gamma_qd, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RoundRotorMachine

const _property_types_RoundRotorMachine = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("R")=>"Float64", Symbol("Td0_p")=>"Float64", Symbol("Td0_pp")=>"Float64", Symbol("Tq0_p")=>"Float64", Symbol("Tq0_pp")=>"Float64", Symbol("Xd")=>"Float64", Symbol("Xq")=>"Float64", Symbol("Xd_p")=>"Float64", Symbol("Xq_p")=>"Float64", Symbol("Xd_pp")=>"Float64", Symbol("Xl")=>"Float64", Symbol("Se")=>"Vector{Float64}", Symbol("gamma_d1")=>"Float64", Symbol("gamma_q1")=>"Float64", Symbol("gamma_d2")=>"Float64", Symbol("gamma_q2")=>"Float64", Symbol("gamma_qd")=>"Float64", )
OpenAPI.property_type(::Type{ RoundRotorMachine }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RoundRotorMachine[name]))}

function OpenAPI.check_required(o::RoundRotorMachine)
    o.id === nothing && (return false)
    o.R === nothing && (return false)
    o.Td0_p === nothing && (return false)
    o.Td0_pp === nothing && (return false)
    o.Tq0_p === nothing && (return false)
    o.Tq0_pp === nothing && (return false)
    o.Xd === nothing && (return false)
    o.Xq === nothing && (return false)
    o.Xd_p === nothing && (return false)
    o.Xq_p === nothing && (return false)
    o.Xd_pp === nothing && (return false)
    o.Xl === nothing && (return false)
    o.Se === nothing && (return false)
    o.gamma_d1 === nothing && (return false)
    o.gamma_q1 === nothing && (return false)
    o.gamma_d2 === nothing && (return false)
    o.gamma_q2 === nothing && (return false)
    o.gamma_qd === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::RoundRotorMachine)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("id"), o.id)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("R"), o.R)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Td0_p"), o.Td0_p)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Td0_pp"), o.Td0_pp)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Tq0_p"), o.Tq0_p)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Tq0_pp"), o.Tq0_pp)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Xd"), o.Xd)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Xq"), o.Xq)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Xd_p"), o.Xd_p)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Xq_p"), o.Xq_p)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Xd_pp"), o.Xd_pp)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Xl"), o.Xl)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("Se"), o.Se)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("gamma_d1"), o.gamma_d1)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("gamma_q1"), o.gamma_q1)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("gamma_d2"), o.gamma_d2)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("gamma_q2"), o.gamma_q2)
    OpenAPI.validate_property(RoundRotorMachine, Symbol("gamma_qd"), o.gamma_qd)
end

function OpenAPI.validate_property(::Type{ RoundRotorMachine }, name::Symbol, val)













    if name === Symbol("Se")
        OpenAPI.validate_param(name, "RoundRotorMachine", :maxItems, val, 2)
        OpenAPI.validate_param(name, "RoundRotorMachine", :minItems, val, 2)
    end





end
