# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RenewableEnergyConverterTypeA

    RenewableEnergyConverterTypeA(;
        id=nothing,
        T_g=nothing,
        Rrpwr=nothing,
        Brkpt=nothing,
        Zerox=nothing,
        Lvpl1=nothing,
        Vo_lim=nothing,
        Lv_pnts=nothing,
        Io_lim=nothing,
        T_fltr=nothing,
        K_hv=nothing,
        Iqr_lims=nothing,
        Accel=nothing,
        Lvpl_sw=nothing,
        Q_ref=1.0,
        R_source=0.0,
        X_source=100000.0,
        states=nothing,
        n_states=3,
    )

    - id::Int64
    - T_g::Float64
    - Rrpwr::Float64
    - Brkpt::Float64
    - Zerox::Float64
    - Lvpl1::Float64
    - Vo_lim::Float64
    - Lv_pnts::MinMax
    - Io_lim::Float64
    - T_fltr::Float64
    - K_hv::Float64
    - Iqr_lims::MinMax
    - Accel::Float64
    - Lvpl_sw::Bool
    - Q_ref::Float64
    - R_source::Float64
    - X_source::Float64
    - states::Vector{String} : Do not modify
    - n_states::Int64 : Do not modify
"""
Base.@kwdef mutable struct RenewableEnergyConverterTypeA <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    T_g::Union{Nothing, Float64} = nothing
    Rrpwr::Union{Nothing, Float64} = nothing
    Brkpt::Union{Nothing, Float64} = nothing
    Zerox::Union{Nothing, Float64} = nothing
    Lvpl1::Union{Nothing, Float64} = nothing
    Vo_lim::Union{Nothing, Float64} = nothing
    Lv_pnts = nothing # spec type: Union{ Nothing, MinMax }
    Io_lim::Union{Nothing, Float64} = nothing
    T_fltr::Union{Nothing, Float64} = nothing
    K_hv::Union{Nothing, Float64} = nothing
    Iqr_lims = nothing # spec type: Union{ Nothing, MinMax }
    Accel::Union{Nothing, Float64} = nothing
    Lvpl_sw::Union{Nothing, Bool} = nothing
    Q_ref::Union{Nothing, Float64} = 1.0
    R_source::Union{Nothing, Float64} = 0.0
    X_source::Union{Nothing, Float64} = 100000.0
    states::Union{Nothing, Vector{String}} = nothing
    n_states::Union{Nothing, Int64} = 3

    function RenewableEnergyConverterTypeA(id, T_g, Rrpwr, Brkpt, Zerox, Lvpl1, Vo_lim, Lv_pnts, Io_lim, T_fltr, K_hv, Iqr_lims, Accel, Lvpl_sw, Q_ref, R_source, X_source, states, n_states, )
        o = new(id, T_g, Rrpwr, Brkpt, Zerox, Lvpl1, Vo_lim, Lv_pnts, Io_lim, T_fltr, K_hv, Iqr_lims, Accel, Lvpl_sw, Q_ref, R_source, X_source, states, n_states, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RenewableEnergyConverterTypeA

const _property_types_RenewableEnergyConverterTypeA = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("T_g")=>"Float64", Symbol("Rrpwr")=>"Float64", Symbol("Brkpt")=>"Float64", Symbol("Zerox")=>"Float64", Symbol("Lvpl1")=>"Float64", Symbol("Vo_lim")=>"Float64", Symbol("Lv_pnts")=>"MinMax", Symbol("Io_lim")=>"Float64", Symbol("T_fltr")=>"Float64", Symbol("K_hv")=>"Float64", Symbol("Iqr_lims")=>"MinMax", Symbol("Accel")=>"Float64", Symbol("Lvpl_sw")=>"Bool", Symbol("Q_ref")=>"Float64", Symbol("R_source")=>"Float64", Symbol("X_source")=>"Float64", Symbol("states")=>"Vector{String}", Symbol("n_states")=>"Int64", )
OpenAPI.property_type(::Type{ RenewableEnergyConverterTypeA }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RenewableEnergyConverterTypeA[name]))}

function OpenAPI.check_required(o::RenewableEnergyConverterTypeA)
    o.id === nothing && (return false)
    o.T_g === nothing && (return false)
    o.Rrpwr === nothing && (return false)
    o.Brkpt === nothing && (return false)
    o.Zerox === nothing && (return false)
    o.Lvpl1 === nothing && (return false)
    o.Vo_lim === nothing && (return false)
    o.Lv_pnts === nothing && (return false)
    o.Io_lim === nothing && (return false)
    o.T_fltr === nothing && (return false)
    o.K_hv === nothing && (return false)
    o.Iqr_lims === nothing && (return false)
    o.Accel === nothing && (return false)
    o.Lvpl_sw === nothing && (return false)
    o.states === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::RenewableEnergyConverterTypeA)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("id"), o.id)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("T_g"), o.T_g)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Rrpwr"), o.Rrpwr)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Brkpt"), o.Brkpt)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Zerox"), o.Zerox)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Lvpl1"), o.Lvpl1)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Vo_lim"), o.Vo_lim)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Lv_pnts"), o.Lv_pnts)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Io_lim"), o.Io_lim)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("T_fltr"), o.T_fltr)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("K_hv"), o.K_hv)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Iqr_lims"), o.Iqr_lims)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Accel"), o.Accel)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Lvpl_sw"), o.Lvpl_sw)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("Q_ref"), o.Q_ref)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("R_source"), o.R_source)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("X_source"), o.X_source)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("states"), o.states)
    OpenAPI.validate_property(RenewableEnergyConverterTypeA, Symbol("n_states"), o.n_states)
end

function OpenAPI.validate_property(::Type{ RenewableEnergyConverterTypeA }, name::Symbol, val)


















    if name === Symbol("states")
        OpenAPI.validate_param(name, "RenewableEnergyConverterTypeA", :enum, val, ["Ip", "Iq", "VMeas"])
    end


end
