# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""Source

    Source(;
        id=nothing,
        name=nothing,
        available=nothing,
        bus=nothing,
        active_power=0.0,
        reactive_power=0.0,
        active_power_limits=nothing,
        reactive_power_limits=nothing,
        R_th=0.0,
        X_th=0.0,
        internal_voltage=1.0,
        internal_angle=0.0,
        base_power=100.0,
        operation_cost=nothing,
        dynamic_injector=nothing,
    )

    - id::Int64
    - name::String
    - available::Bool
    - bus::Int64
    - active_power::Float64
    - reactive_power::Float64
    - active_power_limits::MinMax
    - reactive_power_limits::MinMax
    - R_th::Float64
    - X_th::Float64
    - internal_voltage::Float64
    - internal_angle::Float64
    - base_power::Float64
    - operation_cost::ImportExportCost
    - dynamic_injector::Any
"""
Base.@kwdef mutable struct Source <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    bus::Union{Nothing, Int64} = nothing
    active_power::Union{Nothing, Float64} = 0.0
    reactive_power::Union{Nothing, Float64} = 0.0
    active_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    reactive_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    R_th::Union{Nothing, Float64} = 0.0
    X_th::Union{Nothing, Float64} = 0.0
    internal_voltage::Union{Nothing, Float64} = 1.0
    internal_angle::Union{Nothing, Float64} = 0.0
    base_power::Union{Nothing, Float64} = 100.0
    operation_cost = nothing # spec type: Union{ Nothing, ImportExportCost }
    dynamic_injector::Union{Nothing, Any} = nothing

    function Source(
        id,
        name,
        available,
        bus,
        active_power,
        reactive_power,
        active_power_limits,
        reactive_power_limits,
        R_th,
        X_th,
        internal_voltage,
        internal_angle,
        base_power,
        operation_cost,
        dynamic_injector,
    )
        o = new(
            id,
            name,
            available,
            bus,
            active_power,
            reactive_power,
            active_power_limits,
            reactive_power_limits,
            R_th,
            X_th,
            internal_voltage,
            internal_angle,
            base_power,
            operation_cost,
            dynamic_injector,
        )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Source

const _property_types_Source = Dict{Symbol, String}(
    Symbol("id")=>"Int64",
    Symbol("name")=>"String",
    Symbol("available")=>"Bool",
    Symbol("bus")=>"Int64",
    Symbol("active_power")=>"Float64",
    Symbol("reactive_power")=>"Float64",
    Symbol("active_power_limits")=>"MinMax",
    Symbol("reactive_power_limits")=>"MinMax",
    Symbol("R_th")=>"Float64",
    Symbol("X_th")=>"Float64",
    Symbol("internal_voltage")=>"Float64",
    Symbol("internal_angle")=>"Float64",
    Symbol("base_power")=>"Float64",
    Symbol("operation_cost")=>"ImportExportCost",
    Symbol("dynamic_injector")=>"Any",
)
OpenAPI.property_type(::Type{Source}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_Source[name]))}

function OpenAPI.check_required(o::Source)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.bus === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Source)
    OpenAPI.validate_property(Source, Symbol("id"), o.id)
    OpenAPI.validate_property(Source, Symbol("name"), o.name)
    OpenAPI.validate_property(Source, Symbol("available"), o.available)
    OpenAPI.validate_property(Source, Symbol("bus"), o.bus)
    OpenAPI.validate_property(Source, Symbol("active_power"), o.active_power)
    OpenAPI.validate_property(Source, Symbol("reactive_power"), o.reactive_power)
    OpenAPI.validate_property(Source, Symbol("active_power_limits"), o.active_power_limits)
    OpenAPI.validate_property(
        Source,
        Symbol("reactive_power_limits"),
        o.reactive_power_limits,
    )
    OpenAPI.validate_property(Source, Symbol("R_th"), o.R_th)
    OpenAPI.validate_property(Source, Symbol("X_th"), o.X_th)
    OpenAPI.validate_property(Source, Symbol("internal_voltage"), o.internal_voltage)
    OpenAPI.validate_property(Source, Symbol("internal_angle"), o.internal_angle)
    OpenAPI.validate_property(Source, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(Source, Symbol("operation_cost"), o.operation_cost)
    OpenAPI.validate_property(Source, Symbol("dynamic_injector"), o.dynamic_injector)
end

function OpenAPI.validate_property(::Type{Source}, name::Symbol, val) end
