# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PiecewiseLinearData_points_inner

    PiecewiseLinearDataPointsInner(;
        x=nothing,
        y=nothing,
    )

    - x::Float64
    - y::Float64
"""
Base.@kwdef mutable struct PiecewiseLinearDataPointsInner <: OpenAPI.APIModel
    x::Union{Nothing,Float64} = nothing
    y::Union{Nothing,Float64} = nothing

    function PiecewiseLinearDataPointsInner(x, y)
        OpenAPI.validate_property(PiecewiseLinearDataPointsInner, Symbol("x"), x)
        OpenAPI.validate_property(PiecewiseLinearDataPointsInner, Symbol("y"), y)
        return new(x, y)
    end
end # type PiecewiseLinearDataPointsInner

const _property_types_PiecewiseLinearDataPointsInner =
    Dict{Symbol,String}(Symbol("x") => "Float64", Symbol("y") => "Float64")
OpenAPI.property_type(::Type{PiecewiseLinearDataPointsInner}, name::Symbol) = Union{
    Nothing,
    eval(Base.Meta.parse(_property_types_PiecewiseLinearDataPointsInner[name])),
}

function check_required(o::PiecewiseLinearDataPointsInner)
    o.x === nothing && (return false)
    o.y === nothing && (return false)
    true
end

function OpenAPI.validate_property(
    ::Type{PiecewiseLinearDataPointsInner},
    name::Symbol,
    val,
)


end
