# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""VariableReserve

    VariableReserve(;
        id=nothing,
        name=nothing,
        available=nothing,
        time_frame=nothing,
        requirement=nothing,
        sustained_time=3600.0,
        max_output_fraction=1.0,
        max_participation_factor=1.0,
        deployed_fraction=0.0,
        reserve_direction=nothing,
    )

    - id::Int64
    - name::String
    - available::Bool
    - time_frame::Float64
    - requirement::Float64
    - sustained_time::Float64
    - max_output_fraction::Float64
    - max_participation_factor::Float64
    - deployed_fraction::Float64
    - reserve_direction::String
"""
Base.@kwdef mutable struct VariableReserve <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    time_frame::Union{Nothing, Float64} = nothing
    requirement::Union{Nothing, Float64} = nothing
    sustained_time::Union{Nothing, Float64} = 3600.0
    max_output_fraction::Union{Nothing, Float64} = 1.0
    max_participation_factor::Union{Nothing, Float64} = 1.0
    deployed_fraction::Union{Nothing, Float64} = 0.0
    reserve_direction::Union{Nothing, String} = nothing

    function VariableReserve(
        id,
        name,
        available,
        time_frame,
        requirement,
        sustained_time,
        max_output_fraction,
        max_participation_factor,
        deployed_fraction,
        reserve_direction,
    )
        o = new(
            id,
            name,
            available,
            time_frame,
            requirement,
            sustained_time,
            max_output_fraction,
            max_participation_factor,
            deployed_fraction,
            reserve_direction,
        )
        OpenAPI.validate_properties(o)
        return o
    end
end # type VariableReserve

const _property_types_VariableReserve = Dict{Symbol, String}(
    Symbol("id")=>"Int64",
    Symbol("name")=>"String",
    Symbol("available")=>"Bool",
    Symbol("time_frame")=>"Float64",
    Symbol("requirement")=>"Float64",
    Symbol("sustained_time")=>"Float64",
    Symbol("max_output_fraction")=>"Float64",
    Symbol("max_participation_factor")=>"Float64",
    Symbol("deployed_fraction")=>"Float64",
    Symbol("reserve_direction")=>"String",
)
OpenAPI.property_type(::Type{VariableReserve}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_VariableReserve[name]))}

function OpenAPI.check_required(o::VariableReserve)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.time_frame === nothing && (return false)
    o.requirement === nothing && (return false)
    o.reserve_direction === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::VariableReserve)
    OpenAPI.validate_property(VariableReserve, Symbol("id"), o.id)
    OpenAPI.validate_property(VariableReserve, Symbol("name"), o.name)
    OpenAPI.validate_property(VariableReserve, Symbol("available"), o.available)
    OpenAPI.validate_property(VariableReserve, Symbol("time_frame"), o.time_frame)
    OpenAPI.validate_property(VariableReserve, Symbol("requirement"), o.requirement)
    OpenAPI.validate_property(VariableReserve, Symbol("sustained_time"), o.sustained_time)
    OpenAPI.validate_property(
        VariableReserve,
        Symbol("max_output_fraction"),
        o.max_output_fraction,
    )
    OpenAPI.validate_property(
        VariableReserve,
        Symbol("max_participation_factor"),
        o.max_participation_factor,
    )
    OpenAPI.validate_property(
        VariableReserve,
        Symbol("deployed_fraction"),
        o.deployed_fraction,
    )
    OpenAPI.validate_property(
        VariableReserve,
        Symbol("reserve_direction"),
        o.reserve_direction,
    )
end

function OpenAPI.validate_property(::Type{VariableReserve}, name::Symbol, val)
    if name === Symbol("reserve_direction")
        OpenAPI.validate_param(
            name,
            "VariableReserve",
            :enum,
            val,
            ["UP", "DOWN", "SYMMETRIC"],
        )
    end
end
