# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""MarketBidCost_no_load_cost

    MarketBidCostNoLoadCost(; value=nothing)
"""
mutable struct MarketBidCostNoLoadCost <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Float64, TimeSeriesKey }
    MarketBidCostNoLoadCost() = new()
    MarketBidCostNoLoadCost(value) = new(value)
end # type MarketBidCostNoLoadCost

function OpenAPI.property_type(
    ::Type{MarketBidCostNoLoadCost},
    name::Symbol,
    json::Dict{String, Any},
)

    # no discriminator specified, can't determine the exact type
    return fieldtype(MarketBidCostNoLoadCost, name)
end
