# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RenewableDispatch_operation_cost
Cost representation for renewable generation units

    RenewableDispatchOperationCost(;
        curtailment_cost=nothing,
        variable=nothing,
    )

    - curtailment_cost::CostCurve1
    - variable::CostCurve
"""
Base.@kwdef mutable struct RenewableDispatchOperationCost <: OpenAPI.APIModel
    curtailment_cost = nothing # spec type: Union{ Nothing, CostCurve1 }
    variable = nothing # spec type: Union{ Nothing, CostCurve }

    function RenewableDispatchOperationCost(curtailment_cost, variable)
        OpenAPI.validate_property(
            RenewableDispatchOperationCost,
            Symbol("curtailment_cost"),
            curtailment_cost,
        )
        OpenAPI.validate_property(
            RenewableDispatchOperationCost,
            Symbol("variable"),
            variable,
        )
        return new(curtailment_cost, variable)
    end
end # type RenewableDispatchOperationCost

const _property_types_RenewableDispatchOperationCost = Dict{Symbol,String}(
    Symbol("curtailment_cost") => "CostCurve1",
    Symbol("variable") => "CostCurve",
)
OpenAPI.property_type(::Type{RenewableDispatchOperationCost}, name::Symbol) = Union{
    Nothing,
    eval(Base.Meta.parse(_property_types_RenewableDispatchOperationCost[name])),
}

function check_required(o::RenewableDispatchOperationCost)
    o.variable === nothing && (return false)
    true
end

function OpenAPI.validate_property(
    ::Type{RenewableDispatchOperationCost},
    name::Symbol,
    val,
)


end
