# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""EnergyReservoirStorage_operation_cost_start_up

    EnergyReservoirStorageOperationCostStartUp(; value=nothing)
"""
mutable struct EnergyReservoirStorageOperationCostStartUp <: OpenAPI.OneOfAPIModel
    value::Any # Union{ EnergyReservoirStorageOperationCostStartUpOneOf, Float64 }
    EnergyReservoirStorageOperationCostStartUp() = new()
    EnergyReservoirStorageOperationCostStartUp(value) = new(value)
end # type EnergyReservoirStorageOperationCostStartUp

function OpenAPI.property_type(
    ::Type{EnergyReservoirStorageOperationCostStartUp},
    name::Symbol,
    json::Dict{String,Any},
)

    # no discriminator specified, can't determine the exact type
    return fieldtype(EnergyReservoirStorageOperationCostStartUp, name)
end
