# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""MarketBidCost_incremental_offer_curves
Sell Offer Curves data

    MarketBidCostIncrementalOfferCurves(; value=nothing)
"""
mutable struct MarketBidCostIncrementalOfferCurves <: OpenAPI.OneOfAPIModel
    value::Any # Union{ PiecewiseStepData, TimeSeriesKey }
    MarketBidCostIncrementalOfferCurves() = new()
    MarketBidCostIncrementalOfferCurves(value) = new(value)
end # type MarketBidCostIncrementalOfferCurves

function OpenAPI.property_type(
    ::Type{MarketBidCostIncrementalOfferCurves},
    name::Symbol,
    json::Dict{String, Any},
)

    # no discriminator specified, can't determine the exact type
    return fieldtype(MarketBidCostIncrementalOfferCurves, name)
end
