# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FixedAdmittance_Y

    FixedAdmittanceY(;
        real=nothing,
        imag=nothing,
    )

    - real::Float64
    - imag::Float64
"""
Base.@kwdef mutable struct FixedAdmittanceY <: OpenAPI.APIModel
    real::Union{Nothing,Float64} = nothing
    imag::Union{Nothing,Float64} = nothing

    function FixedAdmittanceY(real, imag)
        OpenAPI.validate_property(FixedAdmittanceY, Symbol("real"), real)
        OpenAPI.validate_property(FixedAdmittanceY, Symbol("imag"), imag)
        return new(real, imag)
    end
end # type FixedAdmittanceY

const _property_types_FixedAdmittanceY =
    Dict{Symbol,String}(Symbol("real") => "Float64", Symbol("imag") => "Float64")
OpenAPI.property_type(::Type{FixedAdmittanceY}, name::Symbol) =
    Union{Nothing,eval(Base.Meta.parse(_property_types_FixedAdmittanceY[name]))}

function check_required(o::FixedAdmittanceY)
    true
end

function OpenAPI.validate_property(::Type{FixedAdmittanceY}, name::Symbol, val)


end
