# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""HydroStorageGenerationCost

    HydroStorageGenerationCost(; value=nothing)
"""
mutable struct HydroStorageGenerationCost <: OpenAPI.OneOfAPIModel
    value::Any # Union{ HydroGenerationCost, StorageCost }
    HydroStorageGenerationCost() = new()
    HydroStorageGenerationCost(value) = new(value)
end # type HydroStorageGenerationCost

function OpenAPI.property_type(
    ::Type{HydroStorageGenerationCost},
    name::Symbol,
    json::Dict{String, Any},
)
    discriminator = json["cost_type"]
    if discriminator == "HYDRO_GEN"
        return eval(Base.Meta.parse("HydroGenerationCost"))
    elseif discriminator == "STORAGE"
        return eval(Base.Meta.parse("StorageCost"))
    end
    throw(
        OpenAPI.ValidationException(
            "Invalid discriminator value: $discriminator for HydroStorageGenerationCost",
        ),
    )
end
