# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MotorLoad

    MotorLoad(;
        id=nothing,
        name=nothing,
        available=nothing,
        bus=nothing,
        active_power=nothing,
        reactive_power=nothing,
        base_power=nothing,
        rating=nothing,
        max_active_power=nothing,
        reactive_power_limits=nothing,
        motor_technology="UNDETERMINED",
        dynamic_injector=nothing,
    )

    - id::Int64
    - name::String
    - available::Bool
    - bus::Int64
    - active_power::Float64
    - reactive_power::Float64
    - base_power::Float64
    - rating::Float64
    - max_active_power::Float64
    - reactive_power_limits::MinMax
    - motor_technology::String
    - dynamic_injector::Any
"""
Base.@kwdef mutable struct MotorLoad <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    bus::Union{Nothing, Int64} = nothing
    active_power::Union{Nothing, Float64} = nothing
    reactive_power::Union{Nothing, Float64} = nothing
    base_power::Union{Nothing, Float64} = nothing
    rating::Union{Nothing, Float64} = nothing
    max_active_power::Union{Nothing, Float64} = nothing
    reactive_power_limits = nothing # spec type: Union{ Nothing, MinMax }
    motor_technology::Union{Nothing, String} = "UNDETERMINED"
    dynamic_injector::Union{Nothing, Any} = nothing

    function MotorLoad(id, name, available, bus, active_power, reactive_power, base_power, rating, max_active_power, reactive_power_limits, motor_technology, dynamic_injector, )
        o = new(id, name, available, bus, active_power, reactive_power, base_power, rating, max_active_power, reactive_power_limits, motor_technology, dynamic_injector, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type MotorLoad

const _property_types_MotorLoad = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("bus")=>"Int64", Symbol("active_power")=>"Float64", Symbol("reactive_power")=>"Float64", Symbol("base_power")=>"Float64", Symbol("rating")=>"Float64", Symbol("max_active_power")=>"Float64", Symbol("reactive_power_limits")=>"MinMax", Symbol("motor_technology")=>"String", Symbol("dynamic_injector")=>"Any", )
OpenAPI.property_type(::Type{ MotorLoad }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MotorLoad[name]))}

function OpenAPI.check_required(o::MotorLoad)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.bus === nothing && (return false)
    o.active_power === nothing && (return false)
    o.reactive_power === nothing && (return false)
    o.base_power === nothing && (return false)
    o.rating === nothing && (return false)
    o.max_active_power === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::MotorLoad)
    OpenAPI.validate_property(MotorLoad, Symbol("id"), o.id)
    OpenAPI.validate_property(MotorLoad, Symbol("name"), o.name)
    OpenAPI.validate_property(MotorLoad, Symbol("available"), o.available)
    OpenAPI.validate_property(MotorLoad, Symbol("bus"), o.bus)
    OpenAPI.validate_property(MotorLoad, Symbol("active_power"), o.active_power)
    OpenAPI.validate_property(MotorLoad, Symbol("reactive_power"), o.reactive_power)
    OpenAPI.validate_property(MotorLoad, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(MotorLoad, Symbol("rating"), o.rating)
    OpenAPI.validate_property(MotorLoad, Symbol("max_active_power"), o.max_active_power)
    OpenAPI.validate_property(MotorLoad, Symbol("reactive_power_limits"), o.reactive_power_limits)
    OpenAPI.validate_property(MotorLoad, Symbol("motor_technology"), o.motor_technology)
    OpenAPI.validate_property(MotorLoad, Symbol("dynamic_injector"), o.dynamic_injector)
end

function OpenAPI.validate_property(::Type{ MotorLoad }, name::Symbol, val)











    if name === Symbol("motor_technology")
        OpenAPI.validate_param(name, "MotorLoad", :enum, val, ["INDUCTION", "SYNCHRONOUS", "UNDETERMINED"])
    end


end
