# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""HeadVolumeFactor

    HeadVolumeFactor(; value=nothing)
"""
mutable struct HeadVolumeFactor <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Float64, InputOutputCurve }
    HeadVolumeFactor() = new()
    HeadVolumeFactor(value) = new(value)
end # type HeadVolumeFactor

function OpenAPI.property_type(
    ::Type{HeadVolumeFactor},
    name::Symbol,
    json::Dict{String, Any},
)
    discriminator = json["curve_type"]
    if discriminator == "INPUT_OUTPUT"
        return eval(Base.Meta.parse("InputOutputCurve"))
    end
    throw(
        OpenAPI.ValidationException(
            "Invalid discriminator value: $discriminator for HeadVolumeFactor",
        ),
    )
end
