# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ReactiveRenewableControllerAB

    ReactiveRenewableControllerAB(;
        id=nothing,
        bus_control=nothing,
        from_branch_control=nothing,
        to_branch_control=nothing,
        branch_id_control=nothing,
        VC_Flag=nothing,
        Ref_Flag=nothing,
        PF_Flag=nothing,
        V_Flag=nothing,
        T_fltr=nothing,
        K_p=nothing,
        K_i=nothing,
        T_ft=nothing,
        T_fv=nothing,
        V_frz=nothing,
        R_c=nothing,
        X_c=nothing,
        K_c=nothing,
        e_lim=nothing,
        dbd_pnts=nothing,
        Q_lim=nothing,
        T_p=nothing,
        Q_lim_inner=nothing,
        V_lim=nothing,
        K_qp=nothing,
        K_qi=nothing,
        Q_ref=1.0,
        V_ref=1.0,
        states=nothing,
        n_states=nothing,
    )

    - id::Int64
    - bus_control::Int64
    - from_branch_control::Int64
    - to_branch_control::Int64
    - branch_id_control::String
    - VC_Flag::Int64 : Voltage Compensator Flag for REPCA1, is this meant to also be 0 or 1?
    - Ref_Flag::Int64
    - PF_Flag::Int64
    - V_Flag::Int64
    - T_fltr::Float64
    - K_p::Float64
    - K_i::Float64
    - T_ft::Float64
    - T_fv::Float64
    - V_frz::Float64
    - R_c::Float64
    - X_c::Float64
    - K_c::Float64
    - e_lim::MinMax
    - dbd_pnts::DbdPnts
    - Q_lim::MinMax
    - T_p::Float64
    - Q_lim_inner::MinMax
    - V_lim::MinMax
    - K_qp::Float64
    - K_qi::Float64
    - Q_ref::Float64
    - V_ref::Float64
    - states::Vector{String} : States of the ReactiveRenewableControllerAB model (dependent on the Flags)
    - n_states::Int64 : Number of states (dependent on the Flags)
"""
Base.@kwdef mutable struct ReactiveRenewableControllerAB <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    bus_control::Union{Nothing, Int64} = nothing
    from_branch_control::Union{Nothing, Int64} = nothing
    to_branch_control::Union{Nothing, Int64} = nothing
    branch_id_control::Union{Nothing, String} = nothing
    VC_Flag::Union{Nothing, Int64} = nothing
    Ref_Flag::Union{Nothing, Int64} = nothing
    PF_Flag::Union{Nothing, Int64} = nothing
    V_Flag::Union{Nothing, Int64} = nothing
    T_fltr::Union{Nothing, Float64} = nothing
    K_p::Union{Nothing, Float64} = nothing
    K_i::Union{Nothing, Float64} = nothing
    T_ft::Union{Nothing, Float64} = nothing
    T_fv::Union{Nothing, Float64} = nothing
    V_frz::Union{Nothing, Float64} = nothing
    R_c::Union{Nothing, Float64} = nothing
    X_c::Union{Nothing, Float64} = nothing
    K_c::Union{Nothing, Float64} = nothing
    e_lim = nothing # spec type: Union{ Nothing, MinMax }
    dbd_pnts = nothing # spec type: Union{ Nothing, DbdPnts }
    Q_lim = nothing # spec type: Union{ Nothing, MinMax }
    T_p::Union{Nothing, Float64} = nothing
    Q_lim_inner = nothing # spec type: Union{ Nothing, MinMax }
    V_lim = nothing # spec type: Union{ Nothing, MinMax }
    K_qp::Union{Nothing, Float64} = nothing
    K_qi::Union{Nothing, Float64} = nothing
    Q_ref::Union{Nothing, Float64} = 1.0
    V_ref::Union{Nothing, Float64} = 1.0
    states::Union{Nothing, Vector{String}} = nothing
    n_states::Union{Nothing, Int64} = nothing

    function ReactiveRenewableControllerAB(id, bus_control, from_branch_control, to_branch_control, branch_id_control, VC_Flag, Ref_Flag, PF_Flag, V_Flag, T_fltr, K_p, K_i, T_ft, T_fv, V_frz, R_c, X_c, K_c, e_lim, dbd_pnts, Q_lim, T_p, Q_lim_inner, V_lim, K_qp, K_qi, Q_ref, V_ref, states, n_states, )
        o = new(id, bus_control, from_branch_control, to_branch_control, branch_id_control, VC_Flag, Ref_Flag, PF_Flag, V_Flag, T_fltr, K_p, K_i, T_ft, T_fv, V_frz, R_c, X_c, K_c, e_lim, dbd_pnts, Q_lim, T_p, Q_lim_inner, V_lim, K_qp, K_qi, Q_ref, V_ref, states, n_states, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ReactiveRenewableControllerAB

const _property_types_ReactiveRenewableControllerAB = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("bus_control")=>"Int64", Symbol("from_branch_control")=>"Int64", Symbol("to_branch_control")=>"Int64", Symbol("branch_id_control")=>"String", Symbol("VC_Flag")=>"Int64", Symbol("Ref_Flag")=>"Int64", Symbol("PF_Flag")=>"Int64", Symbol("V_Flag")=>"Int64", Symbol("T_fltr")=>"Float64", Symbol("K_p")=>"Float64", Symbol("K_i")=>"Float64", Symbol("T_ft")=>"Float64", Symbol("T_fv")=>"Float64", Symbol("V_frz")=>"Float64", Symbol("R_c")=>"Float64", Symbol("X_c")=>"Float64", Symbol("K_c")=>"Float64", Symbol("e_lim")=>"MinMax", Symbol("dbd_pnts")=>"DbdPnts", Symbol("Q_lim")=>"MinMax", Symbol("T_p")=>"Float64", Symbol("Q_lim_inner")=>"MinMax", Symbol("V_lim")=>"MinMax", Symbol("K_qp")=>"Float64", Symbol("K_qi")=>"Float64", Symbol("Q_ref")=>"Float64", Symbol("V_ref")=>"Float64", Symbol("states")=>"Vector{String}", Symbol("n_states")=>"Int64", )
OpenAPI.property_type(::Type{ ReactiveRenewableControllerAB }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ReactiveRenewableControllerAB[name]))}

function OpenAPI.check_required(o::ReactiveRenewableControllerAB)
    o.id === nothing && (return false)
    o.bus_control === nothing && (return false)
    o.from_branch_control === nothing && (return false)
    o.to_branch_control === nothing && (return false)
    o.branch_id_control === nothing && (return false)
    o.VC_Flag === nothing && (return false)
    o.Ref_Flag === nothing && (return false)
    o.PF_Flag === nothing && (return false)
    o.V_Flag === nothing && (return false)
    o.T_fltr === nothing && (return false)
    o.K_p === nothing && (return false)
    o.K_i === nothing && (return false)
    o.T_ft === nothing && (return false)
    o.T_fv === nothing && (return false)
    o.V_frz === nothing && (return false)
    o.R_c === nothing && (return false)
    o.X_c === nothing && (return false)
    o.K_c === nothing && (return false)
    o.e_lim === nothing && (return false)
    o.dbd_pnts === nothing && (return false)
    o.Q_lim === nothing && (return false)
    o.T_p === nothing && (return false)
    o.Q_lim_inner === nothing && (return false)
    o.V_lim === nothing && (return false)
    o.K_qp === nothing && (return false)
    o.K_qi === nothing && (return false)
    o.states === nothing && (return false)
    o.n_states === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ReactiveRenewableControllerAB)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("id"), o.id)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("bus_control"), o.bus_control)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("from_branch_control"), o.from_branch_control)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("to_branch_control"), o.to_branch_control)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("branch_id_control"), o.branch_id_control)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("VC_Flag"), o.VC_Flag)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("Ref_Flag"), o.Ref_Flag)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("PF_Flag"), o.PF_Flag)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("V_Flag"), o.V_Flag)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("T_fltr"), o.T_fltr)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("K_p"), o.K_p)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("K_i"), o.K_i)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("T_ft"), o.T_ft)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("T_fv"), o.T_fv)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("V_frz"), o.V_frz)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("R_c"), o.R_c)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("X_c"), o.X_c)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("K_c"), o.K_c)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("e_lim"), o.e_lim)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("dbd_pnts"), o.dbd_pnts)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("Q_lim"), o.Q_lim)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("T_p"), o.T_p)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("Q_lim_inner"), o.Q_lim_inner)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("V_lim"), o.V_lim)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("K_qp"), o.K_qp)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("K_qi"), o.K_qi)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("Q_ref"), o.Q_ref)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("V_ref"), o.V_ref)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("states"), o.states)
    OpenAPI.validate_property(ReactiveRenewableControllerAB, Symbol("n_states"), o.n_states)
end

function OpenAPI.validate_property(::Type{ ReactiveRenewableControllerAB }, name::Symbol, val)







    if name === Symbol("Ref_Flag")
        OpenAPI.validate_param(name, "ReactiveRenewableControllerAB", :enum, val, [0, 1])
    end


    if name === Symbol("PF_Flag")
        OpenAPI.validate_param(name, "ReactiveRenewableControllerAB", :enum, val, [0, 1])
    end


    if name === Symbol("V_Flag")
        OpenAPI.validate_param(name, "ReactiveRenewableControllerAB", :enum, val, [0, 1])
    end






















end
