# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""DiscreteControlledACBranch

    DiscreteControlledACBranch(;
        id=nothing,
        name=nothing,
        available=nothing,
        active_power_flow=nothing,
        reactive_power_flow=nothing,
        arc=nothing,
        r=nothing,
        x=nothing,
        rating=nothing,
        discrete_branch_type="OTHER",
        branch_status="CLOSED",
    )

    - id::Int64
    - name::String
    - available::Bool
    - active_power_flow::Float64
    - reactive_power_flow::Float64
    - arc::Int64
    - r::Float64
    - x::Float64
    - rating::Float64
    - discrete_branch_type::String
    - branch_status::String
"""
Base.@kwdef mutable struct DiscreteControlledACBranch <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    reactive_power_flow::Union{Nothing, Float64} = nothing
    arc::Union{Nothing, Int64} = nothing
    r::Union{Nothing, Float64} = nothing
    x::Union{Nothing, Float64} = nothing
    rating::Union{Nothing, Float64} = nothing
    discrete_branch_type::Union{Nothing, String} = "OTHER"
    branch_status::Union{Nothing, String} = "CLOSED"

    function DiscreteControlledACBranch(
        id,
        name,
        available,
        active_power_flow,
        reactive_power_flow,
        arc,
        r,
        x,
        rating,
        discrete_branch_type,
        branch_status,
    )
        OpenAPI.validate_property(DiscreteControlledACBranch, Symbol("id"), id)
        OpenAPI.validate_property(DiscreteControlledACBranch, Symbol("name"), name)
        OpenAPI.validate_property(
            DiscreteControlledACBranch,
            Symbol("available"),
            available,
        )
        OpenAPI.validate_property(
            DiscreteControlledACBranch,
            Symbol("active_power_flow"),
            active_power_flow,
        )
        OpenAPI.validate_property(
            DiscreteControlledACBranch,
            Symbol("reactive_power_flow"),
            reactive_power_flow,
        )
        OpenAPI.validate_property(DiscreteControlledACBranch, Symbol("arc"), arc)
        OpenAPI.validate_property(DiscreteControlledACBranch, Symbol("r"), r)
        OpenAPI.validate_property(DiscreteControlledACBranch, Symbol("x"), x)
        OpenAPI.validate_property(DiscreteControlledACBranch, Symbol("rating"), rating)
        OpenAPI.validate_property(
            DiscreteControlledACBranch,
            Symbol("discrete_branch_type"),
            discrete_branch_type,
        )
        OpenAPI.validate_property(
            DiscreteControlledACBranch,
            Symbol("branch_status"),
            branch_status,
        )
        return new(
            id,
            name,
            available,
            active_power_flow,
            reactive_power_flow,
            arc,
            r,
            x,
            rating,
            discrete_branch_type,
            branch_status,
        )
    end
end # type DiscreteControlledACBranch

const _property_types_DiscreteControlledACBranch = Dict{Symbol, String}(
    Symbol("id") => "Int64",
    Symbol("name") => "String",
    Symbol("available") => "Bool",
    Symbol("active_power_flow") => "Float64",
    Symbol("reactive_power_flow") => "Float64",
    Symbol("arc") => "Int64",
    Symbol("r") => "Float64",
    Symbol("x") => "Float64",
    Symbol("rating") => "Float64",
    Symbol("discrete_branch_type") => "String",
    Symbol("branch_status") => "String",
)
OpenAPI.property_type(::Type{DiscreteControlledACBranch}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_DiscreteControlledACBranch[name]))}

function check_required(o::DiscreteControlledACBranch)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.reactive_power_flow === nothing && (return false)
    o.arc === nothing && (return false)
    o.r === nothing && (return false)
    o.x === nothing && (return false)
    o.rating === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{DiscreteControlledACBranch}, name::Symbol, val)
    if name === Symbol("discrete_branch_type")
        OpenAPI.validate_param(
            name,
            "DiscreteControlledACBranch",
            :enum,
            val,
            ["SWITCH", "BREAKER", "OTHER"],
        )
    end

    if name === Symbol("branch_status")
        OpenAPI.validate_param(
            name,
            "DiscreteControlledACBranch",
            :enum,
            val,
            ["OPEN", "CLOSED"],
        )
    end
end
