# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SEXS

    SEXS(;
        id=nothing,
        Ta_Tb=nothing,
        Tb=nothing,
        K=nothing,
        Te=nothing,
        V_lim=nothing,
        V_ref=1.0,
        states_types=nothing,
    )

    - id::Int64
    - Ta_Tb::Float64
    - Tb::Float64
    - K::Float64
    - Te::Float64
    - V_lim::MinMax
    - V_ref::Float64
    - states_types::Vector{String} : Do not modify
"""
Base.@kwdef mutable struct SEXS <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    Ta_Tb::Union{Nothing, Float64} = nothing
    Tb::Union{Nothing, Float64} = nothing
    K::Union{Nothing, Float64} = nothing
    Te::Union{Nothing, Float64} = nothing
    V_lim = nothing # spec type: Union{ Nothing, MinMax }
    V_ref::Union{Nothing, Float64} = 1.0
    states_types::Union{Nothing, Vector{String}} = nothing

    function SEXS(id, Ta_Tb, Tb, K, Te, V_lim, V_ref, states_types, )
        o = new(id, Ta_Tb, Tb, K, Te, V_lim, V_ref, states_types, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SEXS

const _property_types_SEXS = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("Ta_Tb")=>"Float64", Symbol("Tb")=>"Float64", Symbol("K")=>"Float64", Symbol("Te")=>"Float64", Symbol("V_lim")=>"MinMax", Symbol("V_ref")=>"Float64", Symbol("states_types")=>"Vector{String}", )
OpenAPI.property_type(::Type{ SEXS }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SEXS[name]))}

function OpenAPI.check_required(o::SEXS)
    o.id === nothing && (return false)
    o.Ta_Tb === nothing && (return false)
    o.Tb === nothing && (return false)
    o.K === nothing && (return false)
    o.Te === nothing && (return false)
    o.V_lim === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SEXS)
    OpenAPI.validate_property(SEXS, Symbol("id"), o.id)
    OpenAPI.validate_property(SEXS, Symbol("Ta_Tb"), o.Ta_Tb)
    OpenAPI.validate_property(SEXS, Symbol("Tb"), o.Tb)
    OpenAPI.validate_property(SEXS, Symbol("K"), o.K)
    OpenAPI.validate_property(SEXS, Symbol("Te"), o.Te)
    OpenAPI.validate_property(SEXS, Symbol("V_lim"), o.V_lim)
    OpenAPI.validate_property(SEXS, Symbol("V_ref"), o.V_ref)
    OpenAPI.validate_property(SEXS, Symbol("states_types"), o.states_types)
end

function OpenAPI.validate_property(::Type{ SEXS }, name::Symbol, val)








    if name === Symbol("states_types")
        OpenAPI.validate_param(name, "SEXS", :enum, val, ["Differential", "Algebraic", "Hybrid"])
    end

end
