# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VariableReserveNonSpinning

    VariableReserveNonSpinning(;
        id=nothing,
        name=nothing,
        available=nothing,
        time_frame=nothing,
        requirement=nothing,
        sustained_time=14400.0,
        max_output_fraction=1.0,
        max_participation_factor=1.0,
        deployed_fraction=0.0,
    )

    - id::Int64
    - name::String
    - available::Bool
    - time_frame::Float64
    - requirement::Float64
    - sustained_time::Float64
    - max_output_fraction::Float64
    - max_participation_factor::Float64
    - deployed_fraction::Float64
"""
Base.@kwdef mutable struct VariableReserveNonSpinning <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    time_frame::Union{Nothing, Float64} = nothing
    requirement::Union{Nothing, Float64} = nothing
    sustained_time::Union{Nothing, Float64} = 14400.0
    max_output_fraction::Union{Nothing, Float64} = 1.0
    max_participation_factor::Union{Nothing, Float64} = 1.0
    deployed_fraction::Union{Nothing, Float64} = 0.0

    function VariableReserveNonSpinning(id, name, available, time_frame, requirement, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, )
        OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("id"), id)
        OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("name"), name)
        OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("available"), available)
        OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("time_frame"), time_frame)
        OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("requirement"), requirement)
        OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("sustained_time"), sustained_time)
        OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("max_output_fraction"), max_output_fraction)
        OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("max_participation_factor"), max_participation_factor)
        OpenAPI.validate_property(VariableReserveNonSpinning, Symbol("deployed_fraction"), deployed_fraction)
        return new(id, name, available, time_frame, requirement, sustained_time, max_output_fraction, max_participation_factor, deployed_fraction, )
    end
end # type VariableReserveNonSpinning

const _property_types_VariableReserveNonSpinning = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("time_frame")=>"Float64", Symbol("requirement")=>"Float64", Symbol("sustained_time")=>"Float64", Symbol("max_output_fraction")=>"Float64", Symbol("max_participation_factor")=>"Float64", Symbol("deployed_fraction")=>"Float64", )
OpenAPI.property_type(::Type{ VariableReserveNonSpinning }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VariableReserveNonSpinning[name]))}

function check_required(o::VariableReserveNonSpinning)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.time_frame === nothing && (return false)
    o.requirement === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ VariableReserveNonSpinning }, name::Symbol, val)









end
