# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MonitoredLine

    MonitoredLine(;
        id=nothing,
        name=nothing,
        available=nothing,
        active_power_flow=nothing,
        reactive_power_flow=nothing,
        arc=nothing,
        r=nothing,
        x=nothing,
        b=nothing,
        flow_limits=nothing,
        rating=nothing,
        rating_b=nothing,
        rating_c=nothing,
        angle_limits=nothing,
        g=nothing,
    )

    - id::Int64
    - name::String
    - available::Bool
    - active_power_flow::Float64
    - reactive_power_flow::Float64
    - arc::Int64
    - r::Float64
    - x::Float64
    - b::FromTo
    - flow_limits::FromToToFrom
    - rating::Float64
    - rating_b::Float64
    - rating_c::Float64
    - angle_limits::MinMax
    - g::FromTo
"""
Base.@kwdef mutable struct MonitoredLine <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    reactive_power_flow::Union{Nothing, Float64} = nothing
    arc::Union{Nothing, Int64} = nothing
    r::Union{Nothing, Float64} = nothing
    x::Union{Nothing, Float64} = nothing
    b = nothing # spec type: Union{ Nothing, FromTo }
    flow_limits = nothing # spec type: Union{ Nothing, FromToToFrom }
    rating::Union{Nothing, Float64} = nothing
    rating_b::Union{Nothing, Float64} = nothing
    rating_c::Union{Nothing, Float64} = nothing
    angle_limits = nothing # spec type: Union{ Nothing, MinMax }
    g = nothing # spec type: Union{ Nothing, FromTo }

    function MonitoredLine(id, name, available, active_power_flow, reactive_power_flow, arc, r, x, b, flow_limits, rating, rating_b, rating_c, angle_limits, g, )
        OpenAPI.validate_property(MonitoredLine, Symbol("id"), id)
        OpenAPI.validate_property(MonitoredLine, Symbol("name"), name)
        OpenAPI.validate_property(MonitoredLine, Symbol("available"), available)
        OpenAPI.validate_property(MonitoredLine, Symbol("active_power_flow"), active_power_flow)
        OpenAPI.validate_property(MonitoredLine, Symbol("reactive_power_flow"), reactive_power_flow)
        OpenAPI.validate_property(MonitoredLine, Symbol("arc"), arc)
        OpenAPI.validate_property(MonitoredLine, Symbol("r"), r)
        OpenAPI.validate_property(MonitoredLine, Symbol("x"), x)
        OpenAPI.validate_property(MonitoredLine, Symbol("b"), b)
        OpenAPI.validate_property(MonitoredLine, Symbol("flow_limits"), flow_limits)
        OpenAPI.validate_property(MonitoredLine, Symbol("rating"), rating)
        OpenAPI.validate_property(MonitoredLine, Symbol("rating_b"), rating_b)
        OpenAPI.validate_property(MonitoredLine, Symbol("rating_c"), rating_c)
        OpenAPI.validate_property(MonitoredLine, Symbol("angle_limits"), angle_limits)
        OpenAPI.validate_property(MonitoredLine, Symbol("g"), g)
        return new(id, name, available, active_power_flow, reactive_power_flow, arc, r, x, b, flow_limits, rating, rating_b, rating_c, angle_limits, g, )
    end
end # type MonitoredLine

const _property_types_MonitoredLine = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("active_power_flow")=>"Float64", Symbol("reactive_power_flow")=>"Float64", Symbol("arc")=>"Int64", Symbol("r")=>"Float64", Symbol("x")=>"Float64", Symbol("b")=>"FromTo", Symbol("flow_limits")=>"FromToToFrom", Symbol("rating")=>"Float64", Symbol("rating_b")=>"Float64", Symbol("rating_c")=>"Float64", Symbol("angle_limits")=>"MinMax", Symbol("g")=>"FromTo", )
OpenAPI.property_type(::Type{ MonitoredLine }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MonitoredLine[name]))}

function check_required(o::MonitoredLine)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.reactive_power_flow === nothing && (return false)
    o.arc === nothing && (return false)
    o.r === nothing && (return false)
    o.x === nothing && (return false)
    o.b === nothing && (return false)
    o.flow_limits === nothing && (return false)
    o.rating === nothing && (return false)
    o.angle_limits === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ MonitoredLine }, name::Symbol, val)















end
