# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Transformer2W

    Transformer2W(;
        id=nothing,
        name=nothing,
        available=nothing,
        active_power_flow=nothing,
        reactive_power_flow=nothing,
        arc=nothing,
        r=nothing,
        x=nothing,
        primary_shunt=nothing,
        rating=nothing,
        base_power=nothing,
        base_voltage_primary=nothing,
        base_voltage_secondary=nothing,
        rating_b=nothing,
        rating_c=nothing,
        winding_group_number="UNDEFINED",
    )

    - id::Int64
    - name::String
    - available::Bool
    - active_power_flow::Float64
    - reactive_power_flow::Float64
    - arc::Int64
    - r::Float64
    - x::Float64
    - primary_shunt::ComplexNumber
    - rating::Float64
    - base_power::Float64
    - base_voltage_primary::Float64
    - base_voltage_secondary::Float64
    - rating_b::Float64
    - rating_c::Float64
    - winding_group_number::String
"""
Base.@kwdef mutable struct Transformer2W <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    available::Union{Nothing, Bool} = nothing
    active_power_flow::Union{Nothing, Float64} = nothing
    reactive_power_flow::Union{Nothing, Float64} = nothing
    arc::Union{Nothing, Int64} = nothing
    r::Union{Nothing, Float64} = nothing
    x::Union{Nothing, Float64} = nothing
    primary_shunt = nothing # spec type: Union{ Nothing, ComplexNumber }
    rating::Union{Nothing, Float64} = nothing
    base_power::Union{Nothing, Float64} = nothing
    base_voltage_primary::Union{Nothing, Float64} = nothing
    base_voltage_secondary::Union{Nothing, Float64} = nothing
    rating_b::Union{Nothing, Float64} = nothing
    rating_c::Union{Nothing, Float64} = nothing
    winding_group_number::Union{Nothing, String} = "UNDEFINED"

    function Transformer2W(id, name, available, active_power_flow, reactive_power_flow, arc, r, x, primary_shunt, rating, base_power, base_voltage_primary, base_voltage_secondary, rating_b, rating_c, winding_group_number, )
        o = new(id, name, available, active_power_flow, reactive_power_flow, arc, r, x, primary_shunt, rating, base_power, base_voltage_primary, base_voltage_secondary, rating_b, rating_c, winding_group_number, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Transformer2W

const _property_types_Transformer2W = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("available")=>"Bool", Symbol("active_power_flow")=>"Float64", Symbol("reactive_power_flow")=>"Float64", Symbol("arc")=>"Int64", Symbol("r")=>"Float64", Symbol("x")=>"Float64", Symbol("primary_shunt")=>"ComplexNumber", Symbol("rating")=>"Float64", Symbol("base_power")=>"Float64", Symbol("base_voltage_primary")=>"Float64", Symbol("base_voltage_secondary")=>"Float64", Symbol("rating_b")=>"Float64", Symbol("rating_c")=>"Float64", Symbol("winding_group_number")=>"String", )
OpenAPI.property_type(::Type{ Transformer2W }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Transformer2W[name]))}

function OpenAPI.check_required(o::Transformer2W)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.active_power_flow === nothing && (return false)
    o.reactive_power_flow === nothing && (return false)
    o.arc === nothing && (return false)
    o.r === nothing && (return false)
    o.x === nothing && (return false)
    o.primary_shunt === nothing && (return false)
    o.base_power === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Transformer2W)
    OpenAPI.validate_property(Transformer2W, Symbol("id"), o.id)
    OpenAPI.validate_property(Transformer2W, Symbol("name"), o.name)
    OpenAPI.validate_property(Transformer2W, Symbol("available"), o.available)
    OpenAPI.validate_property(Transformer2W, Symbol("active_power_flow"), o.active_power_flow)
    OpenAPI.validate_property(Transformer2W, Symbol("reactive_power_flow"), o.reactive_power_flow)
    OpenAPI.validate_property(Transformer2W, Symbol("arc"), o.arc)
    OpenAPI.validate_property(Transformer2W, Symbol("r"), o.r)
    OpenAPI.validate_property(Transformer2W, Symbol("x"), o.x)
    OpenAPI.validate_property(Transformer2W, Symbol("primary_shunt"), o.primary_shunt)
    OpenAPI.validate_property(Transformer2W, Symbol("rating"), o.rating)
    OpenAPI.validate_property(Transformer2W, Symbol("base_power"), o.base_power)
    OpenAPI.validate_property(Transformer2W, Symbol("base_voltage_primary"), o.base_voltage_primary)
    OpenAPI.validate_property(Transformer2W, Symbol("base_voltage_secondary"), o.base_voltage_secondary)
    OpenAPI.validate_property(Transformer2W, Symbol("rating_b"), o.rating_b)
    OpenAPI.validate_property(Transformer2W, Symbol("rating_c"), o.rating_c)
    OpenAPI.validate_property(Transformer2W, Symbol("winding_group_number"), o.winding_group_number)
end

function OpenAPI.validate_property(::Type{ Transformer2W }, name::Symbol, val)
















    if name === Symbol("winding_group_number")
        OpenAPI.validate_param(name, "Transformer2W", :enum, val, ["UNDEFINED", "GROUP_0", "GROUP_1", "GROUP_5", "GROUP_6", "GROUP_7", "GROUP_11"])
    end

end
