# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MinMax_1

    MinMax1(;
        max=nothing,
        min=nothing,
    )

    - max::Float64
    - min::Float64
"""
Base.@kwdef mutable struct MinMax1 <: OpenAPI.APIModel
    max::Union{Nothing, Float64} = nothing
    min::Union{Nothing, Float64} = nothing

    function MinMax1(max, min, )
        OpenAPI.validate_property(MinMax1, Symbol("max"), max)
        OpenAPI.validate_property(MinMax1, Symbol("min"), min)
        return new(max, min, )
    end
end # type MinMax1

const _property_types_MinMax1 = Dict{Symbol,String}(Symbol("max")=>"Float64", Symbol("min")=>"Float64", )
OpenAPI.property_type(::Type{ MinMax1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MinMax1[name]))}

function check_required(o::MinMax1)
    true
end

function OpenAPI.validate_property(::Type{ MinMax1 }, name::Symbol, val)


end
