# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SteamTurbineGov1

    SteamTurbineGov1(;
        id=nothing,
        R=nothing,
        T1=nothing,
        valve_position_limits=nothing,
        T2=nothing,
        T3=nothing,
        D_T=nothing,
        DB_h=nothing,
        DB_l=nothing,
        T_rate=nothing,
        P_ref=nothing,
        states=nothing,
        n_states=2,
        states_types=nothing,
    )

    - id::Int64
    - R::Float64
    - T1::Float64
    - valve_position_limits::MinMax
    - T2::Float64
    - T3::Float64
    - D_T::Float64
    - DB_h::Float64
    - DB_l::Float64
    - T_rate::Float64
    - P_ref::Float64
    - states::Vector{String}
    - n_states::Int64 : Do not modify
    - states_types::Vector{String} : Do not modify
"""
Base.@kwdef mutable struct SteamTurbineGov1 <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    R::Union{Nothing, Float64} = nothing
    T1::Union{Nothing, Float64} = nothing
    valve_position_limits = nothing # spec type: Union{ Nothing, MinMax }
    T2::Union{Nothing, Float64} = nothing
    T3::Union{Nothing, Float64} = nothing
    D_T::Union{Nothing, Float64} = nothing
    DB_h::Union{Nothing, Float64} = nothing
    DB_l::Union{Nothing, Float64} = nothing
    T_rate::Union{Nothing, Float64} = nothing
    P_ref::Union{Nothing, Float64} = nothing
    states::Union{Nothing, Vector{String}} = nothing
    n_states::Union{Nothing, Int64} = 2
    states_types::Union{Nothing, Vector{String}} = nothing

    function SteamTurbineGov1(id, R, T1, valve_position_limits, T2, T3, D_T, DB_h, DB_l, T_rate, P_ref, states, n_states, states_types, )
        o = new(id, R, T1, valve_position_limits, T2, T3, D_T, DB_h, DB_l, T_rate, P_ref, states, n_states, states_types, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SteamTurbineGov1

const _property_types_SteamTurbineGov1 = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("R")=>"Float64", Symbol("T1")=>"Float64", Symbol("valve_position_limits")=>"MinMax", Symbol("T2")=>"Float64", Symbol("T3")=>"Float64", Symbol("D_T")=>"Float64", Symbol("DB_h")=>"Float64", Symbol("DB_l")=>"Float64", Symbol("T_rate")=>"Float64", Symbol("P_ref")=>"Float64", Symbol("states")=>"Vector{String}", Symbol("n_states")=>"Int64", Symbol("states_types")=>"Vector{String}", )
OpenAPI.property_type(::Type{ SteamTurbineGov1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SteamTurbineGov1[name]))}

function OpenAPI.check_required(o::SteamTurbineGov1)
    o.id === nothing && (return false)
    o.R === nothing && (return false)
    o.T1 === nothing && (return false)
    o.valve_position_limits === nothing && (return false)
    o.T2 === nothing && (return false)
    o.T3 === nothing && (return false)
    o.D_T === nothing && (return false)
    o.DB_h === nothing && (return false)
    o.DB_l === nothing && (return false)
    o.T_rate === nothing && (return false)
    o.states === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SteamTurbineGov1)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("id"), o.id)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("R"), o.R)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("T1"), o.T1)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("valve_position_limits"), o.valve_position_limits)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("T2"), o.T2)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("T3"), o.T3)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("D_T"), o.D_T)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("DB_h"), o.DB_h)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("DB_l"), o.DB_l)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("T_rate"), o.T_rate)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("P_ref"), o.P_ref)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("states"), o.states)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("n_states"), o.n_states)
    OpenAPI.validate_property(SteamTurbineGov1, Symbol("states_types"), o.states_types)
end

function OpenAPI.validate_property(::Type{ SteamTurbineGov1 }, name::Symbol, val)












    if name === Symbol("states")
        OpenAPI.validate_param(name, "SteamTurbineGov1", :enum, val, ["x_g1", "x_g2"])
    end



    if name === Symbol("states_types")
        OpenAPI.validate_param(name, "SteamTurbineGov1", :enum, val, ["Differential", "Algebraic", "Hybrid"])
    end

end
