# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""HydroEnergyReservoir_operation_cost

    HydroEnergyReservoirOperationCost(; value=nothing)
"""
mutable struct HydroEnergyReservoirOperationCost <: OpenAPI.OneOfAPIModel
    value::Any # Union{ EnergyReservoirStorageOperationCost, HydroDispatchOperationCost }
    HydroEnergyReservoirOperationCost() = new()
    HydroEnergyReservoirOperationCost(value) = new(value)
end # type HydroEnergyReservoirOperationCost

function OpenAPI.property_type(
    ::Type{HydroEnergyReservoirOperationCost},
    name::Symbol,
    json::Dict{String,Any},
)

    # no discriminator specified, can't determine the exact type
    return fieldtype(HydroEnergyReservoirOperationCost, name)
end
