# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""CostCurve_value_curve

    CostCurveValueCurve(; value=nothing)
"""
mutable struct CostCurveValueCurve <: OpenAPI.OneOfAPIModel
    value::Any # Union{ AverageRateCurve, IncrementalCurve, InputOutputCurve }
    CostCurveValueCurve() = new()
    CostCurveValueCurve(value) = new(value)
end # type CostCurveValueCurve

function OpenAPI.property_type(
    ::Type{CostCurveValueCurve},
    name::Symbol,
    json::Dict{String,Any},
)
    discriminator = json["curve_type"]
    if discriminator == "AVERAGE_RATE"
        return eval(Base.Meta.parse("AverageRateCurve"))
    elseif discriminator == "INCREMENTAL"
        return eval(Base.Meta.parse("IncrementalCurve"))
    elseif discriminator == "INPUT_OUTPUT"
        return eval(Base.Meta.parse("InputOutputCurve"))
    end
    throw(
        OpenAPI.ValidationException(
            "Invalid discriminator value: $discriminator for CostCurveValueCurve",
        ),
    )
end
