function openapi2psy(thermal::ThermalStandard, resolver::Resolver)
    PSY.ThermalStandard(;
        name=thermal.name,
        prime_mover=get_prime_mover_enum(thermal.prime_mover_type),
        fuel_type=get_fuel_type_enum(thermal.fuel_type),
        rating=thermal.rating,
        base_power=thermal.base_power,
        available=thermal.available,
        status=thermal.status,
        time_at_status=thermal.time_at_status,
        active_power=thermal.active_power,
        reactive_power=thermal.reactive_power,
        active_power_limits=get_tuple_from_min_max(thermal.active_power_limits),
        reactive_power_limits=get_tuple_min_max(thermal.reactive_power_limits),
        ramp_limits=get_tuple_up_down(thermal.ramp_limits),
        operation_cost=get_thermal_cost(thermal.operation_cost),
        time_limits=get_tuple_up_down(thermal.time_limits),
        must_run=thermal.must_run,
        bus=resolver(thermal.bus),
    )
end
